// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_laravelforge

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LaravelforgeProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type LaravelforgeModel struct {
}
