// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_deployment_webhooks

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DeploymentWebhooksResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the deployment webhook was created.",
				MarkdownDescription: "The date and time the deployment webhook was created.",
			},
			"deployment_webhook": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The deployment webhook ID",
				MarkdownDescription: "The deployment webhook ID",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The site ID",
				MarkdownDescription: "The site ID",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the deployment webhook was last updated.",
				MarkdownDescription: "The date and time the deployment webhook was last updated.",
			},
			"url": schema.StringAttribute{
				Required:            true,
				Description:         "The URL of the deployment webhook.",
				MarkdownDescription: "The URL of the deployment webhook.",
			},
		},
	}
}

type DeploymentWebhooksModel struct {
	CreatedAt         types.String `tfsdk:"created_at"`
	DeploymentWebhook types.Int64  `tfsdk:"deployment_webhook"`
	Id                types.String `tfsdk:"id"`
	Organization      types.String `tfsdk:"organization"`
	Server            types.Int64  `tfsdk:"server"`
	Site              types.Int64  `tfsdk:"site"`
	UpdatedAt         types.String `tfsdk:"updated_at"`
	Url               types.String `tfsdk:"url"`
}
