{
    "openapi": "3.1.0",
    "info": {
        "title": "Forge",
        "version": "0.0.1",
        "description": "Laravel Forge - API Documentation"
    },
    "servers": [
        {
            "url": "https://forge.laravel.com/api"
        }
    ],
    "tags": [
        {
            "name": "Roles"
        },
        {
            "name": "Sites"
        },
        {
            "name": "Organizations"
        },
        {
            "name": "Recipes"
        },
        {
            "name": "Servers"
        },
        {
            "name": "Background Processes"
        },
        {
            "name": "Nginx"
        },
        {
            "name": "Databases"
        },
        {
            "name": "Monitors"
        },
        {
            "name": "Firewall Rules"
        },
        {
            "name": "Logs"
        },
        {
            "name": "SSH Keys"
        },
        {
            "name": "Scheduled Jobs"
        },
        {
            "name": "Security Rules"
        },
        {
            "name": "Redirect Rules"
        },
        {
            "name": "Integrations"
        },
        {
            "name": "Deployments"
        },
        {
            "name": "Commands"
        },
        {
            "name": "Teams"
        },
        {
            "name": "Server Credentials"
        },
        {
            "name": "User"
        },
        {
            "name": "Providers"
        }
    ],
    "security": [
        {
            "http": []
        },
        {
            "oauth2": []
        }
    ],
    "paths": {
        "/orgs/{organization}/servers/{server}/background-processes": {
            "get": {
                "operationId": "organizations.servers.background-processes.index",
                "description": "List all background processes on the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List background processes",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.background-processes.store",
                "description": "Create a new background process from a template.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create background process",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}": {
            "get": {
                "operationId": "organizations.servers.background-processes.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get background process",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.background-processes.update",
                "description": "Update the supervisor configuration for a background process.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update background process",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.background-processes.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete background process",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}/log": {
            "get": {
                "operationId": "organizations.servers.background-processes.log.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get background process log",
                "tags": [
                    "Background Processes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/commands": {
            "get": {
                "operationId": "organizations.servers.sites.commands.index",
                "description": "List all command runs for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List commands",
                "tags": [
                    "Commands"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.commands.store",
                "description": "Run a command on the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create command",
                "tags": [
                    "Commands"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-commands"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-commands"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/commands/{command}": {
            "get": {
                "operationId": "organizations.servers.sites.commands.show",
                "description": "Get a specific command run.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get command",
                "tags": [
                    "Commands"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.commands.destroy",
                "description": "Delete a command history.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete command",
                "tags": [
                    "Commands"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-commands"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-commands"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/commands/{command}/output": {
            "get": {
                "operationId": "organizations.servers.sites.commands.output.show",
                "description": "Get the output of a specific command run.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get command output",
                "tags": [
                    "Commands"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/database/schemas": {
            "get": {
                "operationId": "organizations.servers.database.schemas.index",
                "description": "List all database schemas associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List database schemas",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.database.schemas.store",
                "description": "Add a new database schema to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create database schema",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/database/schemas/{database}": {
            "get": {
                "operationId": "organizations.servers.database.schemas.show",
                "description": "Get a specific database schema associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get database schema",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.database.schemas.destroy",
                "description": "Remove a database schema from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete database schema",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/database/schemas/synchronizations": {
            "post": {
                "operationId": "organizations.servers.database.schemas.synchronizations.store",
                "description": "Synchronize all database schemas on the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update database schemas",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/database/users": {
            "get": {
                "operationId": "organizations.servers.database.users.index",
                "description": "List all database users associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List database users",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.database.users.store",
                "description": "Add a new database user to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create database user",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/database/users/{databaseUser}": {
            "get": {
                "operationId": "organizations.servers.database.users.show",
                "description": "Get a specific database user associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get database user",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.database.users.update",
                "description": "Update a database user on the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update database user",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.database.users.destroy",
                "description": "Remove a database user from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete database user",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-databases"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-databases"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/database/password": {
            "put": {
                "operationId": "organizations.servers.database.password.update",
                "description": "Update the password for the database on the server.\nIt will only update the password Forge thinks is the password, it will not change the password on the server itself.\nThis should only be used if you have changed the password on the server itself and want to update Forge.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update the password for the database",
                "tags": [
                    "Databases"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/webhooks": {
            "get": {
                "operationId": "organizations.servers.sites.webhooks.index",
                "description": "List all webhooks for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List site webhooks",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-notifications"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.webhooks.store",
                "description": "Create a new webhook for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create site webhook",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-notifications"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-notifications"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/webhooks/{deploymentWebhook}": {
            "get": {
                "operationId": "organizations.servers.sites.webhooks.show",
                "description": "Get a specific webhook associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site webhook",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-notifications"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.webhooks.destroy",
                "description": "Delete a specific webhook from the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site webhook",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-notifications"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-notifications"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.index",
                "description": "Show all recent deployments for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List deployments",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.deployments.store",
                "description": "Trigger a new deployment for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create deployment",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/status": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.status.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get deployment status",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.deployments.status.destroy",
                "description": "Reset the deployment state for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update deployment state",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/script": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.script.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get deployment script",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.deployments.script.update",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update deployment script",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/deploy-hook": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.deploy-hook.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get the deployment trigger URL",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.deployments.deploy-hook.update",
                "description": "Regenerate the deployment hook token used for triggering deployment on the deployment URL.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update deployment trigger URL",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/push-to-deploy": {
            "post": {
                "operationId": "organizations.servers.sites.deployments.push-to-deploy.store",
                "description": "Enable push to deploy for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create push to deploy configuration",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.deployments.push-to-deploy.destroy",
                "description": "Disable push to deploy for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete push to deploy configuration",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/{deployment}": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.show",
                "description": "Show a specific deployment.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get deployment",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/deployments/{deployment}/log": {
            "get": {
                "operationId": "organizations.servers.sites.deployments.log.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get deployment output",
                "tags": [
                    "Deployments"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-deploys"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-deploys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/firewall-rules": {
            "get": {
                "operationId": "organizations.servers.firewall-rules.index",
                "description": "List all firewall rules associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server firewall rules",
                "tags": [
                    "Firewall Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-network"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-network"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.firewall-rules.store",
                "description": "Add a new firewall rule to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create server firewall rule",
                "tags": [
                    "Firewall Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-network"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-network"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/firewall-rules/{rule}": {
            "get": {
                "operationId": "organizations.servers.firewall-rules.show",
                "description": "Get a specific firewall rule associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server firewall rule",
                "tags": [
                    "Firewall Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-network"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-network"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.firewall-rules.destroy",
                "description": "Remove a firewall rule from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete server firewall rule",
                "tags": [
                    "Firewall Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-network"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-network"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/horizon": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.horizon.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Horizon integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.horizon.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Horizon integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.horizon.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Horizon integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/octane": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.octane.show",
                "description": "Show whether Laravel Octane integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Octane integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.octane.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Octane integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.octane.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Octane integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/reverb": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.reverb.show",
                "description": "Show whether Laravel Reverb integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Reverb integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.reverb.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Reverb integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.reverb.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Reverb integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/inertia": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.inertia.show",
                "description": "Show whether Inertia SSR integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Inertia integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.inertia.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Inertia integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/pulse": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.pulse.show",
                "description": "Show whether Laravel Pulse integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Pulse integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.pulse.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Pulse integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.pulse.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Pulse integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/laravel-maintenance": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.laravel-maintenance.show",
                "description": "Show whether Laravel Maintenance integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Maintenance integration status",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.laravel-maintenance.store",
                "description": "Enable maintenance mode for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Maintenance integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-commands"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-commands"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.laravel-maintenance.destroy",
                "description": "Disable maintenance mode for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Maintenance integration",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-commands"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-commands"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/integrations/laravel-scheduler": {
            "get": {
                "operationId": "organizations.servers.sites.integrations.laravel-scheduler.show",
                "description": "Show whether Laravel Scheduler integration is enabled.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Laravel Scheduler integration job",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.integrations.laravel-scheduler.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Laravel Scheduler integration job",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-schedulers"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-schedulers"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.integrations.laravel-scheduler.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Laravel Scheduler integration job",
                "tags": [
                    "Integrations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-schedulers"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-schedulers"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/logs/{key}": {
            "get": {
                "operationId": "organizations.servers.logs.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server log content",
                "tags": [
                    "Logs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.logs.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete server log content",
                "tags": [
                    "Logs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/monitors": {
            "get": {
                "operationId": "organizations.servers.monitors.index",
                "description": "List all monitors associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server monitors",
                "tags": [
                    "Monitors"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.monitors.store",
                "description": "Add a new monitor to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create server monitor",
                "tags": [
                    "Monitors"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-monitors"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-monitors"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/monitors/{monitor}": {
            "get": {
                "operationId": "organizations.servers.monitors.show",
                "description": "Get a specific monitor associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server monitor",
                "tags": [
                    "Monitors"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.monitors.destroy",
                "description": "Remove a monitor from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete server monitor",
                "tags": [
                    "Monitors"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-monitors"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-monitors"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/nginx/templates": {
            "get": {
                "operationId": "organizations.servers.nginx.templates.index",
                "description": "List all nginx templates for the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List Nginx templates",
                "tags": [
                    "Nginx"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.nginx.templates.store",
                "description": "Create a new nginx template on the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create Nginx template",
                "tags": [
                    "Nginx"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-nginx-templates"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-nginx-templates"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/nginx/templates/{nginxTemplate}": {
            "get": {
                "operationId": "organizations.servers.nginx.templates.show",
                "description": "Get a specific nginx template associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Nginx template",
                "tags": [
                    "Nginx"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.nginx.templates.update",
                "description": "Update the specified nginx template on the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update Nginx template",
                "tags": [
                    "Nginx"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-nginx-templates"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-nginx-templates"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.nginx.templates.destroy",
                "description": "Delete the specified nginx template from the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete Nginx template",
                "tags": [
                    "Nginx"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-nginx-templates"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-nginx-templates"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs": {
            "get": {
                "operationId": "organizations.index",
                "description": "Show all organizations the user has access to.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List organizations",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}": {
            "get": {
                "operationId": "organizations.show",
                "description": "Show a specific organization for the user.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get organization",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [
                    "organization:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/server-credentials": {
            "get": {
                "operationId": "organizations.server-credentials.index",
                "description": "Show all server credentials for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server credentials",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/server-credentials/{credential}": {
            "get": {
                "operationId": "organizations.server-credentials.show",
                "description": "Show a specific server credential for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server credential",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/server-credentials/{credential}/regions/{region}/vpcs": {
            "post": {
                "operationId": "organizations.server-credentials.vpcs.store",
                "description": "Create a private network for the provider.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create a new VPC",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "get": {
                "operationId": "organizations.server-credentials.vpcs.index",
                "description": "List VPCs for the provider.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List VPCs",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/server-credentials/{credential}/regions/{region}/vpcs/{vpcId}": {
            "get": {
                "operationId": "organizations.server-credentials.vpcs.show",
                "description": "Get a VPC for the provider.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get VPC",
                "tags": [
                    "Organizations"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers": {
            "get": {
                "operationId": "providers.index",
                "description": "Show all providers\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List providers",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}": {
            "get": {
                "operationId": "providers.show",
                "description": "Show the provider.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get provider",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/sizes": {
            "get": {
                "operationId": "providers.sizes.index",
                "description": "Show all providers\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List provider sizes",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/sizes/{providerSize}": {
            "get": {
                "operationId": "providers.sizes.show",
                "description": "Show the provider size.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get provider size",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/regions": {
            "get": {
                "operationId": "providers.regions.index",
                "description": "Show all provider regions\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List provider regions",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/regions/{providerRegion}": {
            "get": {
                "operationId": "providers.regions.show",
                "description": "Show the provider region.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get provider region",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/regions/{providerRegion}/sizes": {
            "get": {
                "operationId": "providers.regions.sizes.index",
                "description": "Show all provider region sizes\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List provider region sizes",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/providers/{provider}/regions/{providerRegion}/sizes/{providerSize}": {
            "get": {
                "operationId": "providers.regions.sizes.show",
                "description": "Show the provider region size.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get provider region size",
                "tags": [
                    "Providers"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/recipes": {
            "get": {
                "operationId": "organizations.recipes.index",
                "description": "Show all recipes for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List organization recipes",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organization.recipes.store",
                "description": "Create a new recipe for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create recipe",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/recipes/{recipe}": {
            "get": {
                "operationId": "organizations.recipes.show",
                "description": "Show the recipe for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get recipe",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.recipes.update",
                "description": "Update a recipe in the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update recipe",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.recipes.destroy",
                "description": "Delete a recipe from the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete recipe",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/recipes/{recipe}/runs": {
            "get": {
                "operationId": "organizations.recipes.runs.index",
                "description": "Show all runs for the recipe.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List recipe runs",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.recipes.runs.store",
                "description": "Run a given recipe on a list of servers.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create recipe run",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/recipes/{recipe}/runs/{log}": {
            "get": {
                "operationId": "organizations.recipes.runs.show",
                "description": "Show a specific run for the recipe.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get recipe run",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/teams/{team}/recipes": {
            "get": {
                "operationId": "organizations.teams.recipes.index",
                "description": "Show all recipes for the team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List team recipes",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.teams.recipes.store",
                "description": "Shares a recipe with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Share recipe with the team",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:manage",
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view",
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/teams/{team}/recipes/{recipe}": {
            "delete": {
                "operationId": "organizations.teams.recipes.destroy",
                "description": "Unshare a recipe with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete a recipe share",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:manage",
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "recipe:view",
                    "recipe:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/forge-recipes": {
            "get": {
                "operationId": "forge-recipes.index",
                "description": "Show all Forge provided recipes.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List Forge's recipes",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/forge-recipes/{forgeRecipe}": {
            "get": {
                "operationId": "forge-recipes.show",
                "description": "Show the Forge recipe.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Forge recipe",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/forge-recipes/{forgeRecipe}/runs": {
            "post": {
                "operationId": "forge-recipes.runs.store",
                "description": "Run a Forge recipe on specified servers.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create Forge recipe run",
                "tags": [
                    "Recipes"
                ],
                "security": [
                    {
                        "oauth2": [
                            "recipe:view"
                        ]
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules": {
            "get": {
                "operationId": "organizations.servers.sites.redirect-rules.index",
                "description": "List all redirect rules associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List site redirect rules",
                "tags": [
                    "Redirect Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-redirects"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-redirects"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.redirect-rules.store",
                "description": "Add a new redirect rule to the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create site redirect rule",
                "tags": [
                    "Redirect Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-redirects"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-redirects"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/redirect-rules/{redirectRule}": {
            "get": {
                "operationId": "organizations.servers.sites.redirect-rules.show",
                "description": "Get a specific redirect rule associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site redirect rule",
                "tags": [
                    "Redirect Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-redirects"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-redirects"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.redirect-rules.destroy",
                "description": "Remove a redirect rule from the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site redirect rule",
                "tags": [
                    "Redirect Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-redirects"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-redirects"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/predefined-roles": {
            "get": {
                "operationId": "predefined-roles.index",
                "description": "Show all predefined roles.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List predefined roles",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/predefined-roles/{role}": {
            "get": {
                "operationId": "predefined-roles.show",
                "description": "Show a specific predefined role.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get predefined role",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/permissions": {
            "get": {
                "operationId": "permissions.index",
                "description": "Show all permissions.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List permissions",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/permissions/{permission}": {
            "get": {
                "operationId": "permissions.show",
                "description": "Show a specific permission.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get permission",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": []
                    }
                ],
                "x-permissions": [],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/roles": {
            "post": {
                "operationId": "organizations.roles.store",
                "description": "Create a new role for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create role",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "get": {
                "operationId": "organizations.roles.index",
                "description": "Show all roles for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List roles",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/roles/{role}": {
            "get": {
                "operationId": "organizations.roles.show",
                "description": "Show a specific role for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get role",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.roles.update",
                "description": "Update a role for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update role",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.roles.destroy",
                "description": "Delete a role from the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete role",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:manage"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:manage"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/roles/{role}/permissions": {
            "get": {
                "operationId": "organizations.roles.permissions.index",
                "description": "Show all permissions for the role.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List role permissions",
                "tags": [
                    "Roles"
                ],
                "security": [
                    {
                        "oauth2": [
                            "organization:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "organization:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/ssh-keys": {
            "get": {
                "operationId": "organizations.servers.ssh-keys.index",
                "description": "List all SSH keys associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server SSH keys",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.ssh-keys.store",
                "description": "Add a new SSH key to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create server SSH key",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-keys"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-keys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/ssh-keys/{key}": {
            "get": {
                "operationId": "organizations.servers.ssh-keys.show",
                "description": "Get a specific SSH key associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server SSH key",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.ssh-keys.destroy",
                "description": "Remove an SSH key from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete server SSH key",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete-keys"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete-keys"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/key": {
            "get": {
                "operationId": "organizations.servers.key.show",
                "description": "Get the public SSH key for the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server public SSH key",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:archive"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.key.update",
                "description": "Regenerate the SSH key pair for the server and return the new public key.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update server public SSH key",
                "tags": [
                    "SSH Keys"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:archive"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:archive"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/scheduled-jobs": {
            "get": {
                "operationId": "organizations.servers.scheduled-jobs.index",
                "description": "List all scheduled jobs associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server scheduled jobs",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.scheduled-jobs.store",
                "description": "Create a specific scheduled job.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/scheduled-jobs/{job}": {
            "get": {
                "operationId": "organizations.servers.scheduled-jobs.show",
                "description": "Show a specific scheduled job.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.scheduled-jobs.destroy",
                "description": "Delete a specific scheduled job.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/scheduled-jobs/{job}/output": {
            "get": {
                "operationId": "organizations.servers.scheduled-jobs.outputs.show",
                "description": "Show a specific scheduled job output.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get scheduled job output",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/scheduled-jobs": {
            "get": {
                "operationId": "organizations.servers.sites.scheduled-jobs.index",
                "description": "List all scheduled jobs associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List site scheduled jobs",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.scheduled-jobs.store",
                "description": "Create a specific scheduled job for the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create site scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/scheduled-jobs/{job}": {
            "get": {
                "operationId": "organizations.servers.sites.scheduled-jobs.show",
                "description": "Show a specific scheduled job.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.scheduled-jobs.destroy",
                "description": "Delete a specific scheduled job associated with the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site scheduled job",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/scheduled-jobs/{job}/output": {
            "get": {
                "operationId": "organizations.servers.sites.scheduled-jobs.outputs.show",
                "description": "Show a specific scheduled job output associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site scheduled job output",
                "tags": [
                    "Scheduled Jobs"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/security-rules": {
            "get": {
                "operationId": "organizations.servers.sites.security-rules.index",
                "description": "List all security rules associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List site security rules",
                "tags": [
                    "Security Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-security"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-security"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.security-rules.store",
                "description": "Add a new security rule to the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create site security rule",
                "tags": [
                    "Security Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-security"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-security"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/security-rules/{securityRule}": {
            "get": {
                "operationId": "organizations.servers.sites.security-rules.show",
                "description": "Get a specific security rule associated with the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site security rule",
                "tags": [
                    "Security Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-security"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-security"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.security-rules.update",
                "description": "Update an existing security rule for a site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update site security rule",
                "tags": [
                    "Security Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-security"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-security"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.security-rules.destroy",
                "description": "Remove a security rule from the site.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site security rule",
                "tags": [
                    "Security Rules"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-security"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-security"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/teams/{team}/server-credentials": {
            "get": {
                "operationId": "organizations.teams.server-credentials.index",
                "description": "Show all server credentials for the team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List team server credentials",
                "tags": [
                    "Server Credentials"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.teams.server-credentials.store",
                "description": "Share a server credential with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create a new server credential share",
                "tags": [
                    "Server Credentials"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:manage",
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:manage",
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/teams/{team}/server-credentials/{credential}": {
            "delete": {
                "operationId": "organizations.teams.server-credentials.destroy",
                "description": "Unshare a server credential with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete a server credential share",
                "tags": [
                    "Server Credentials"
                ],
                "security": [
                    {
                        "oauth2": [
                            "credential:manage",
                            "credential:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "credential:manage",
                    "credential:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers": {
            "get": {
                "operationId": "organizations.servers.index",
                "description": "Show all servers for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List servers",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.store",
                "description": "Create a new server in the organization. Supports both standard cloud providers\nand custom VPS configurations.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/archives": {
            "get": {
                "operationId": "organizations.servers.archives.index",
                "description": "Get all archived servers for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List archived servers",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.archives.store",
                "description": "Archive a server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create an archived server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:archive"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:archive"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/archives/{server}": {
            "delete": {
                "operationId": "organizations.servers.archives.destroy",
                "description": "Unarchive a server.\nMake sure you have regenerated the server key and added it to the server before unarchiving.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete archived server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:archive"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:archive"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/background-processes/{backgroundProcess}/actions": {
            "post": {
                "operationId": "organizations.servers.background-processes.actions.store",
                "description": "Run an action on a server-level background process.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform an action on a server background process",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create-daemons"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:create-daemons"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/actions": {
            "post": {
                "operationId": "organizations.servers.actions.store",
                "description": "Run an action on a server, defined by the action type parameter.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create server action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/nginx/actions": {
            "post": {
                "operationId": "organizations.servers.services.nginx.actions.store",
                "description": "Run an action on the Nginx service.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform Nginx action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/postgres/actions": {
            "post": {
                "operationId": "organizations.servers.services.postgres.actions.store",
                "description": "Run an action on the Postgres service.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform Postgres action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/redis/actions": {
            "post": {
                "operationId": "organizations.servers.services.redis.actions.store",
                "description": "Run an action on the Redis service.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform Redis action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/mysql/actions": {
            "post": {
                "operationId": "organizations.servers.services.mysql.actions.store",
                "description": "Run an action on the MySQL service.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform MySQL action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/php/actions": {
            "post": {
                "operationId": "organizations.servers.services.php.actions.store",
                "description": "Run an action on a specific PHP version.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform PHP action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/services/supervisor/actions": {
            "post": {
                "operationId": "organizations.servers.services.supervisor.actions.store",
                "description": "Run an action on the Supervisor service.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Perform Supervisor action",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-services"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-services"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}": {
            "get": {
                "operationId": "organizations.servers.show",
                "description": "Show a specific server for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.destroy",
                "description": "Delete a server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:delete"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:delete"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/events": {
            "get": {
                "operationId": "organizations.servers.events.index",
                "description": "List all events associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List server events",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/events/{event}": {
            "get": {
                "operationId": "organizations.servers.events.show",
                "description": "Get a specific event associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server event",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/events/{event}/output": {
            "get": {
                "operationId": "organizations.servers.events.output.show",
                "description": "Get the output for a specific event associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server event output",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/php/cli-version": {
            "get": {
                "operationId": "organizations.servers.php.cli-version.show",
                "description": "Show the PHP CLI version which has been set for the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP CLI version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.cli-version.update",
                "description": "Update the PHP CLI version for the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update PHP CLI version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/site-version": {
            "get": {
                "operationId": "organizations.servers.php.site-version.show",
                "description": "Show the PHP site version which has been set for the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP site version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.site-version.update",
                "description": "Update the PHP site version for the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update PHP site version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/versions": {
            "get": {
                "operationId": "organizations.servers.php.versions.index",
                "description": "List all PHP versions installed on the server\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List PHP versions for server",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.php.versions.store",
                "description": "Install a new PHP version on the server\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Install new PHP version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/versions/{phpVersion}": {
            "get": {
                "operationId": "organizations.servers.php.versions.show",
                "description": "Show the PHP version which has been installed on the server\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.versions.update",
                "description": "Update PHP version to the latest patch release\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update installed PHP version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.php.versions.destroy",
                "description": "Uninstall the PHP version from the server\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete installed PHP version",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/versions/{phpVersion}/configs/fpm": {
            "get": {
                "operationId": "organizations.servers.php.versions.configs.fpm.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP version FPM config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.versions.configs.fpm.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update PHP version FPM config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/versions/{phpVersion}/configs/cli": {
            "get": {
                "operationId": "organizations.servers.php.versions.configs.cli.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP version CLI config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.versions.configs.cli.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update PHP version CLI config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/versions/{phpVersion}/configs/pool": {
            "get": {
                "operationId": "organizations.servers.php.versions.configs.pool.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get PHP version pool config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.versions.configs.pool.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update PHP version pool config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/max-upload-size": {
            "get": {
                "operationId": "organizations.servers.php.max-upload-size.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server PHP max upload size",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.max-upload-size.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update server PHP max upload size",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/max-execution-time": {
            "get": {
                "operationId": "organizations.servers.php.max-execution-time.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server PHP max execution time",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.php.max-execution-time.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update server PHP max execution time",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/php/opcache": {
            "get": {
                "operationId": "organizations.servers.php.opcache.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get server PHP OPcache status",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.php.opcache.store",
                "description": "Enable PHP OPcache for the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create PHP OPcache config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.php.opcache.destroy",
                "description": "Disable PHP OPcache for the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete PHP OPcache config",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-php"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-php"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/teams/{team}/servers": {
            "get": {
                "operationId": "organizations.teams.servers.index",
                "description": "Show all servers for the team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List team servers",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.teams.servers.store",
                "description": "Share a server with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create a new server share",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view",
                    "team:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/teams/{team}/servers/{server}": {
            "delete": {
                "operationId": "organizations.teams.servers.destroy",
                "description": "Unshare a server with a team.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Delete a server share",
                "tags": [
                    "Servers"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view",
                    "team:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/sites": {
            "get": {
                "operationId": "sites.index",
                "description": "Show all sites the current token has access to.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List sites",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/sites": {
            "get": {
                "operationId": "organizations.sites.index",
                "description": "Show all sites for the organization.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List sites for Organization",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/sites/{site}": {
            "get": {
                "operationId": "organizations.sites.show",
                "description": "Show the specified site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites": {
            "get": {
                "operationId": "organizations.servers.sites.index",
                "description": "List all sites associated with the server.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List sites for server",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.store",
                "description": "Add a new site to the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}": {
            "put": {
                "operationId": "organizations.servers.sites.update",
                "description": "Update a site on the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:create"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:create"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.destroy",
                "description": "Remove a site from the server.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:delete"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:delete"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains": {
            "get": {
                "operationId": "organizations.servers.sites.domains.index",
                "description": "Show all domains for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List domains",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.domains.store",
                "description": "Add a new domain to the site\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create domain",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}": {
            "get": {
                "operationId": "organizations.servers.sites.domains.show",
                "description": "Show the specified domain for the site\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get domain",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "patch": {
                "operationId": "organizations.servers.sites.domains.update",
                "description": "Update an existing domain for the site\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update domain",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.domains.destroy",
                "description": "Remove a domain from the site\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete domain",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}/configurations": {
            "get": {
                "operationId": "organizations.servers.sites.domains.configurations",
                "description": "Show the DNS configuration instructions for a domain.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get domain DNS configuration",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}/actions": {
            "post": {
                "operationId": "organizations.servers.sites.domains.actions.store",
                "description": "Run an action on a domain, defined by the action type parameter.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create domain action",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}/nginx": {
            "get": {
                "operationId": "organizations.servers.sites.domains.nginx.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get domain Nginx configuration",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-nginx"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.domains.nginx.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update domain Nginx configuration",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-nginx"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-nginx"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}/certificate": {
            "get": {
                "operationId": "organizations.servers.sites.domains.certificate.show",
                "description": "Get the certificate for a given domain.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get domain certificate",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.domains.certificate.store",
                "description": "Create a new certificate for a given domain.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create domain certificate",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-ssl"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-ssl"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.domains.certificate.destroy",
                "description": "Delete the certificate for a given domain.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete domain certificate",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-ssl"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-ssl"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/domains/{domainRecord}/certificate/actions": {
            "post": {
                "operationId": "organizations.servers.sites.domains.certificate.actions.store",
                "description": "Run an action on a domain certificate, defined by the action type parameter.\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create domain certificate action",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:meta"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:meta"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/healthcheck": {
            "get": {
                "operationId": "organizations.servers.sites.healthcheck.show",
                "description": "Show the healthcheck endpoint that has been set for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get healthcheck endpoint",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-project"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-project"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.healthcheck.update",
                "description": "Update the healthcheck endpoint for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Update healthcheck endpoint",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-project"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-project"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/environment": {
            "get": {
                "operationId": "organizations.servers.sites.environment.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get .env content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.environment.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update .env content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-environment"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-environment"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/nginx": {
            "get": {
                "operationId": "organizations.servers.sites.nginx.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Nginx configuration",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-nginx"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.nginx.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update Nginx configuration",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-nginx"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-nginx"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/composer/credentials": {
            "get": {
                "operationId": "organizations.servers.sites.composer.credentials.index",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get composer credentials for the site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.composer.credentials.store",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Create composer credentials for the site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-packages"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-packages"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/composer/credentials/{repository}": {
            "get": {
                "operationId": "organizations.servers.sites.composer.credentials.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get composer credential for the site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.composer.credentials.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update composer credentials for the site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-packages"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-packages"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            },
            "delete": {
                "operationId": "organizations.servers.sites.composer.credentials.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete composer credentials for the site",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-packages"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-packages"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/load-balancing-nodes": {
            "get": {
                "operationId": "organizations.servers.sites.load-balancing-nodes.index",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List load balancing nodes",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-project"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-project"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "put": {
                "operationId": "organizations.servers.sites.load-balancing-nodes.update",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Update load balancing nodes",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-project"
                        ]
                    }
                ],
                "x-permissions": [
                    "site:manage-project"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/logs/nginx-access": {
            "get": {
                "operationId": "organizations.servers.sites.logs.nginx-access.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Nginx access log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.logs.nginx-access.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Nginx access log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/logs/nginx-error": {
            "get": {
                "operationId": "organizations.servers.sites.logs.nginx-error.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get Nginx error log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.logs.nginx-error.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete Nginx error log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/logs/application": {
            "get": {
                "operationId": "organizations.servers.sites.logs.application.show",
                "description": "\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Get site log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "delete": {
                "operationId": "organizations.servers.sites.logs.application.destroy",
                "description": "\n\nProcessing mode: <small><code>async</code></small>",
                "summary": "Delete site log content",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:manage-logs"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:manage-logs"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "async"
            }
        },
        "/orgs/{organization}/servers/{server}/sites/{site}/heartbeats": {
            "get": {
                "operationId": "organizations.servers.sites.heartbeats.index",
                "description": "Show all heartbeats for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "List heartbeats",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "server:view"
                        ]
                    }
                ],
                "x-permissions": [
                    "server:view"
                ],
                "x-mint": {
                    "metadata": {
                        "noindex": true
                    }
                },
                "x-processingMode": "sync"
            },
            "post": {
                "operationId": "organizations.servers.sites.heartbeats.store",
                "description": "Create a new heartbeat for the site.\n\nProcessing mode: <small><code>sync</code></small>",
                "summary": "Create heartbeat",
                "tags": [
                    "Sites"
                ],
                "security": [
                    {
                        "oauth2": [
                            "site:manage-heartbeats"
                        ]
                    }
                ],
                "x-permissions": [
[...]
