// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_database_users

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DatabaseUsersResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the database user was created.",
				MarkdownDescription: "The date and time the database user was created.",
			},
			"database_ids": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Optional:            true,
				Computed:            true,
				Description:         "The IDs of the databases to assign the user to.",
				MarkdownDescription: "The IDs of the databases to assign the user to.",
			},
			"database_user": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The database user ID",
				MarkdownDescription: "The database user ID",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the database user to create.",
				MarkdownDescription: "The name of the database user to create.",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"password": schema.StringAttribute{
				Required:            true,
				Description:         "The password for the database user.",
				MarkdownDescription: "The password for the database user.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
				},
			},
			"read_only": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether the user should have read-only access to the databases.",
				MarkdownDescription: "Whether the user should have read-only access to the databases.",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"status": schema.StringAttribute{
				Computed:            true,
				Description:         "The status of the database user.",
				MarkdownDescription: "The status of the database user.",
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the database user was last updated.",
				MarkdownDescription: "The date and time the database user was last updated.",
			},
		},
	}
}

type DatabaseUsersModel struct {
	CreatedAt    types.String `tfsdk:"created_at"`
	DatabaseIds  types.List   `tfsdk:"database_ids"`
	DatabaseUser types.Int64  `tfsdk:"database_user"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Organization types.String `tfsdk:"organization"`
	Password     types.String `tfsdk:"password"`
	ReadOnly     types.Bool   `tfsdk:"read_only"`
	Server       types.Int64  `tfsdk:"server"`
	Status       types.String `tfsdk:"status"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}
