// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_domain_certificates

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func DomainCertificatesResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"clone": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"certificate_id": schema.Int64Attribute{
						Optional:            true,
						Computed:            true,
						Description:         "The ID of the certificate to clone.",
						MarkdownDescription: "The ID of the certificate to clone.",
					},
				},
				CustomType: CloneType{
					ObjectType: types.ObjectType{
						AttrTypes: CloneValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the certificate was created.",
				MarkdownDescription: "The date and time the certificate was created.",
			},
			"csr": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"city": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The city for the CSR.",
						MarkdownDescription: "The city for the CSR.",
					},
					"country": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The country for the CSR.",
						MarkdownDescription: "The country for the CSR.",
					},
					"department": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The department for the CSR.",
						MarkdownDescription: "The department for the CSR.",
					},
					"domain": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The domain to generate a CSR for.",
						MarkdownDescription: "The domain to generate a CSR for.",
					},
					"organization": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The organization for the CSR.",
						MarkdownDescription: "The organization for the CSR.",
					},
					"sans": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The SANs for the CSR, comma-separated.",
						MarkdownDescription: "The SANs for the CSR, comma-separated.",
					},
					"state": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The state for the CSR.",
						MarkdownDescription: "The state for the CSR.",
					},
				},
				CustomType: CsrType{
					ObjectType: types.ObjectType{
						AttrTypes: CsrValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "The configuration for a CSR (Certificate Signing Request).",
				MarkdownDescription: "The configuration for a CSR (Certificate Signing Request).",
			},
			"domain_record": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The domain record ID",
				MarkdownDescription: "The domain record ID",
			},
			"existing": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"certificate": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The certificate chain for an existing certificate.",
						MarkdownDescription: "The certificate chain for an existing certificate.",
					},
					"key": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The private key for an existing certificate.",
						MarkdownDescription: "The private key for an existing certificate.",
					},
				},
				CustomType: ExistingType{
					ObjectType: types.ObjectType{
						AttrTypes: ExistingValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "The configuration for an existing certificate.",
				MarkdownDescription: "The configuration for an existing certificate.",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"key_type": schema.StringAttribute{
				Computed: true,
			},
			"letsencrypt": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"key_type": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"ecdsa",
								"rsa",
							),
						},
					},
					"preferred_chain": schema.StringAttribute{
						Optional:            true,
						Computed:            true,
						Description:         "The preferred chain for the Let's Encrypt certificate.",
						MarkdownDescription: "The preferred chain for the Let's Encrypt certificate.",
						Validators: []validator.String{
							stringvalidator.OneOf(
								"ISRG Root X1",
							),
						},
					},
					"verification_method": schema.StringAttribute{
						Optional: true,
						Computed: true,
						Validators: []validator.String{
							stringvalidator.OneOf(
								"http-01",
								"dns-01",
							),
						},
					},
				},
				CustomType: LetsencryptType{
					ObjectType: types.ObjectType{
						AttrTypes: LetsencryptValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Computed:            true,
				Description:         "The configuration for a Let's Encrypt certificate.",
				MarkdownDescription: "The configuration for a Let's Encrypt certificate.",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"preferred_chain": schema.StringAttribute{
				Computed:            true,
				Description:         "The preferred chain for Let's Encrypt certificates.",
				MarkdownDescription: "The preferred chain for Let's Encrypt certificates.",
			},
			"request_status": schema.StringAttribute{
				Computed: true,
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The site ID",
				MarkdownDescription: "The site ID",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required:            true,
				Description:         "The type of certificate to create.",
				MarkdownDescription: "The type of certificate to create.",
				Validators: []validator.String{
					stringvalidator.OneOf(
						"letsencrypt",
						"csr",
						"existing",
						"clone",
					),
				},
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the certificate was last updated.",
				MarkdownDescription: "The date and time the certificate was last updated.",
			},
			"verification_method": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type DomainCertificatesModel struct {
	Clone              CloneValue       `tfsdk:"clone"`
	CreatedAt          types.String     `tfsdk:"created_at"`
	Csr                CsrValue         `tfsdk:"csr"`
	DomainRecord       types.Int64      `tfsdk:"domain_record"`
	Existing           ExistingValue    `tfsdk:"existing"`
	Id                 types.String     `tfsdk:"id"`
	KeyType            types.String     `tfsdk:"key_type"`
	Letsencrypt        LetsencryptValue `tfsdk:"letsencrypt"`
	Organization       types.String     `tfsdk:"organization"`
	PreferredChain     types.String     `tfsdk:"preferred_chain"`
	RequestStatus      types.String     `tfsdk:"request_status"`
	Server             types.Int64      `tfsdk:"server"`
	Site               types.Int64      `tfsdk:"site"`
	Status             types.String     `tfsdk:"status"`
	Type               types.String     `tfsdk:"type"`
	UpdatedAt          types.String     `tfsdk:"updated_at"`
	VerificationMethod types.String     `tfsdk:"verification_method"`
}

var _ basetypes.ObjectTypable = CloneType{}

type CloneType struct {
	basetypes.ObjectType
}

func (t CloneType) Equal(o attr.Type) bool {
	other, ok := o.(CloneType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CloneType) String() string {
	return "CloneType"
}

func (t CloneType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	certificateIdAttribute, ok := attributes["certificate_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certificate_id is missing from object`)

		return nil, diags
	}

	certificateIdVal, ok := certificateIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certificate_id expected to be basetypes.Int64Value, was: %T`, certificateIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CloneValue{
		CertificateId: certificateIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewCloneValueNull() CloneValue {
	return CloneValue{
		state: attr.ValueStateNull,
	}
}

func NewCloneValueUnknown() CloneValue {
	return CloneValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCloneValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CloneValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CloneValue Attribute Value",
				"While creating a CloneValue value, a missing attribute value was detected. "+
					"A CloneValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CloneValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CloneValue Attribute Type",
				"While creating a CloneValue value, an invalid attribute value was detected. "+
					"A CloneValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CloneValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CloneValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CloneValue Attribute Value",
				"While creating a CloneValue value, an extra attribute value was detected. "+
					"A CloneValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CloneValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCloneValueUnknown(), diags
	}

	certificateIdAttribute, ok := attributes["certificate_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certificate_id is missing from object`)

		return NewCloneValueUnknown(), diags
	}

	certificateIdVal, ok := certificateIdAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certificate_id expected to be basetypes.Int64Value, was: %T`, certificateIdAttribute))
	}

	if diags.HasError() {
		return NewCloneValueUnknown(), diags
	}

	return CloneValue{
		CertificateId: certificateIdVal,
		state:         attr.ValueStateKnown,
	}, diags
}

func NewCloneValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CloneValue {
	object, diags := NewCloneValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCloneValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CloneType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCloneValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCloneValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCloneValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCloneValueMust(CloneValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CloneType) ValueType(ctx context.Context) attr.Value {
	return CloneValue{}
}

var _ basetypes.ObjectValuable = CloneValue{}

type CloneValue struct {
	CertificateId basetypes.Int64Value `tfsdk:"certificate_id"`
	state         attr.ValueState
}

func (v CloneValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["certificate_id"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.CertificateId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["certificate_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CloneValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CloneValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CloneValue) String() string {
	return "CloneValue"
}

func (v CloneValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"certificate_id": basetypes.Int64Type{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"certificate_id": v.CertificateId,
		})

	return objVal, diags
}

func (v CloneValue) Equal(o attr.Value) bool {
	other, ok := o.(CloneValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.CertificateId.Equal(other.CertificateId) {
		return false
	}

	return true
}

func (v CloneValue) Type(ctx context.Context) attr.Type {
	return CloneType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CloneValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"certificate_id": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = CsrType{}

type CsrType struct {
	basetypes.ObjectType
}

func (t CsrType) Equal(o attr.Type) bool {
	other, ok := o.(CsrType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CsrType) String() string {
	return "CsrType"
}

func (t CsrType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	cityAttribute, ok := attributes["city"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`city is missing from object`)

		return nil, diags
	}

	cityVal, ok := cityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`city expected to be basetypes.StringValue, was: %T`, cityAttribute))
	}

	countryAttribute, ok := attributes["country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`country is missing from object`)

		return nil, diags
	}

	countryVal, ok := countryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`country expected to be basetypes.StringValue, was: %T`, countryAttribute))
	}

	departmentAttribute, ok := attributes["department"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`department is missing from object`)

		return nil, diags
	}

	departmentVal, ok := departmentAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`department expected to be basetypes.StringValue, was: %T`, departmentAttribute))
	}

	domainAttribute, ok := attributes["domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain is missing from object`)

		return nil, diags
	}

	domainVal, ok := domainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain expected to be basetypes.StringValue, was: %T`, domainAttribute))
	}

	organizationAttribute, ok := attributes["organization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization is missing from object`)

		return nil, diags
	}

	organizationVal, ok := organizationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization expected to be basetypes.StringValue, was: %T`, organizationAttribute))
	}

	sansAttribute, ok := attributes["sans"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sans is missing from object`)

		return nil, diags
	}

	sansVal, ok := sansAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sans expected to be basetypes.StringValue, was: %T`, sansAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return nil, diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CsrValue{
		City:         cityVal,
		Country:      countryVal,
		Department:   departmentVal,
		Domain:       domainVal,
		Organization: organizationVal,
		Sans:         sansVal,
		State:        stateVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCsrValueNull() CsrValue {
	return CsrValue{
		state: attr.ValueStateNull,
	}
}

func NewCsrValueUnknown() CsrValue {
	return CsrValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCsrValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CsrValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CsrValue Attribute Value",
				"While creating a CsrValue value, a missing attribute value was detected. "+
					"A CsrValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CsrValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CsrValue Attribute Type",
				"While creating a CsrValue value, an invalid attribute value was detected. "+
					"A CsrValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CsrValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CsrValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CsrValue Attribute Value",
				"While creating a CsrValue value, an extra attribute value was detected. "+
					"A CsrValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CsrValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCsrValueUnknown(), diags
	}

	cityAttribute, ok := attributes["city"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`city is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	cityVal, ok := cityAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`city expected to be basetypes.StringValue, was: %T`, cityAttribute))
	}

	countryAttribute, ok := attributes["country"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`country is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	countryVal, ok := countryAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`country expected to be basetypes.StringValue, was: %T`, countryAttribute))
	}

	departmentAttribute, ok := attributes["department"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`department is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	departmentVal, ok := departmentAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`department expected to be basetypes.StringValue, was: %T`, departmentAttribute))
	}

	domainAttribute, ok := attributes["domain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`domain is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	domainVal, ok := domainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`domain expected to be basetypes.StringValue, was: %T`, domainAttribute))
	}

	organizationAttribute, ok := attributes["organization"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`organization is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	organizationVal, ok := organizationAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`organization expected to be basetypes.StringValue, was: %T`, organizationAttribute))
	}

	sansAttribute, ok := attributes["sans"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`sans is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	sansVal, ok := sansAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`sans expected to be basetypes.StringValue, was: %T`, sansAttribute))
	}

	stateAttribute, ok := attributes["state"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`state is missing from object`)

		return NewCsrValueUnknown(), diags
	}

	stateVal, ok := stateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`state expected to be basetypes.StringValue, was: %T`, stateAttribute))
	}

	if diags.HasError() {
		return NewCsrValueUnknown(), diags
	}

	return CsrValue{
		City:         cityVal,
		Country:      countryVal,
		Department:   departmentVal,
		Domain:       domainVal,
		Organization: organizationVal,
		Sans:         sansVal,
		State:        stateVal,
		state:        attr.ValueStateKnown,
	}, diags
}

func NewCsrValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CsrValue {
	object, diags := NewCsrValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCsrValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CsrType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCsrValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCsrValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCsrValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCsrValueMust(CsrValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CsrType) ValueType(ctx context.Context) attr.Value {
	return CsrValue{}
}

var _ basetypes.ObjectValuable = CsrValue{}

type CsrValue struct {
	City         basetypes.StringValue `tfsdk:"city"`
	Country      basetypes.StringValue `tfsdk:"country"`
	Department   basetypes.StringValue `tfsdk:"department"`
	Domain       basetypes.StringValue `tfsdk:"domain"`
	Organization basetypes.StringValue `tfsdk:"organization"`
	Sans         basetypes.StringValue `tfsdk:"sans"`
	State        basetypes.StringValue `tfsdk:"state"`
	state        attr.ValueState
}

func (v CsrValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 7)

	var val tftypes.Value
	var err error

	attrTypes["city"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["country"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["department"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["domain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["organization"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["sans"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["state"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 7)

		val, err = v.City.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["city"] = val

		val, err = v.Country.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["country"] = val

		val, err = v.Department.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["department"] = val

		val, err = v.Domain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["domain"] = val

		val, err = v.Organization.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["organization"] = val

		val, err = v.Sans.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["sans"] = val

		val, err = v.State.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["state"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CsrValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CsrValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CsrValue) String() string {
	return "CsrValue"
}

func (v CsrValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"city":         basetypes.StringType{},
		"country":      basetypes.StringType{},
		"department":   basetypes.StringType{},
		"domain":       basetypes.StringType{},
		"organization": basetypes.StringType{},
		"sans":         basetypes.StringType{},
		"state":        basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"city":         v.City,
			"country":      v.Country,
			"department":   v.Department,
			"domain":       v.Domain,
			"organization": v.Organization,
			"sans":         v.Sans,
			"state":        v.State,
		})

	return objVal, diags
}

func (v CsrValue) Equal(o attr.Value) bool {
	other, ok := o.(CsrValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.City.Equal(other.City) {
		return false
	}

	if !v.Country.Equal(other.Country) {
		return false
	}

	if !v.Department.Equal(other.Department) {
		return false
	}

	if !v.Domain.Equal(other.Domain) {
		return false
	}

	if !v.Organization.Equal(other.Organization) {
		return false
	}

	if !v.Sans.Equal(other.Sans) {
		return false
	}

	if !v.State.Equal(other.State) {
		return false
	}

	return true
}

func (v CsrValue) Type(ctx context.Context) attr.Type {
	return CsrType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CsrValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"city":         basetypes.StringType{},
		"country":      basetypes.StringType{},
		"department":   basetypes.StringType{},
		"domain":       basetypes.StringType{},
		"organization": basetypes.StringType{},
		"sans":         basetypes.StringType{},
		"state":        basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = ExistingType{}

type ExistingType struct {
	basetypes.ObjectType
}

func (t ExistingType) Equal(o attr.Type) bool {
	other, ok := o.(ExistingType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t ExistingType) String() string {
	return "ExistingType"
}

func (t ExistingType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	certificateAttribute, ok := attributes["certificate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certificate is missing from object`)

		return nil, diags
	}

	certificateVal, ok := certificateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certificate expected to be basetypes.StringValue, was: %T`, certificateAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return ExistingValue{
		Certificate: certificateVal,
		Key:         keyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewExistingValueNull() ExistingValue {
	return ExistingValue{
		state: attr.ValueStateNull,
	}
}

func NewExistingValueUnknown() ExistingValue {
	return ExistingValue{
		state: attr.ValueStateUnknown,
	}
}

func NewExistingValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (ExistingValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing ExistingValue Attribute Value",
				"While creating a ExistingValue value, a missing attribute value was detected. "+
					"A ExistingValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExistingValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid ExistingValue Attribute Type",
				"While creating a ExistingValue value, an invalid attribute value was detected. "+
					"A ExistingValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("ExistingValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("ExistingValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra ExistingValue Attribute Value",
				"While creating a ExistingValue value, an extra attribute value was detected. "+
					"A ExistingValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra ExistingValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewExistingValueUnknown(), diags
	}

	certificateAttribute, ok := attributes["certificate"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`certificate is missing from object`)

		return NewExistingValueUnknown(), diags
	}

	certificateVal, ok := certificateAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`certificate expected to be basetypes.StringValue, was: %T`, certificateAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewExistingValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	if diags.HasError() {
		return NewExistingValueUnknown(), diags
	}

	return ExistingValue{
		Certificate: certificateVal,
		Key:         keyVal,
		state:       attr.ValueStateKnown,
	}, diags
}

func NewExistingValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) ExistingValue {
	object, diags := NewExistingValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewExistingValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t ExistingType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewExistingValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewExistingValueUnknown(), nil
	}

	if in.IsNull() {
		return NewExistingValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewExistingValueMust(ExistingValue{}.AttributeTypes(ctx), attributes), nil
}

func (t ExistingType) ValueType(ctx context.Context) attr.Value {
	return ExistingValue{}
}

var _ basetypes.ObjectValuable = ExistingValue{}

type ExistingValue struct {
	Certificate basetypes.StringValue `tfsdk:"certificate"`
	Key         basetypes.StringValue `tfsdk:"key"`
	state       attr.ValueState
}

func (v ExistingValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["certificate"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Certificate.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["certificate"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v ExistingValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v ExistingValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v ExistingValue) String() string {
	return "ExistingValue"
}

func (v ExistingValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"certificate": basetypes.StringType{},
		"key":         basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"certificate": v.Certificate,
			"key":         v.Key,
		})

	return objVal, diags
}

func (v ExistingValue) Equal(o attr.Value) bool {
	other, ok := o.(ExistingValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Certificate.Equal(other.Certificate) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	return true
}

func (v ExistingValue) Type(ctx context.Context) attr.Type {
	return ExistingType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v ExistingValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"certificate": basetypes.StringType{},
		"key":         basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = LetsencryptType{}

type LetsencryptType struct {
	basetypes.ObjectType
}

func (t LetsencryptType) Equal(o attr.Type) bool {
	other, ok := o.(LetsencryptType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LetsencryptType) String() string {
	return "LetsencryptType"
}

func (t LetsencryptType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	keyTypeAttribute, ok := attributes["key_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_type is missing from object`)

		return nil, diags
	}

	keyTypeVal, ok := keyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_type expected to be basetypes.StringValue, was: %T`, keyTypeAttribute))
	}

	preferredChainAttribute, ok := attributes["preferred_chain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`preferred_chain is missing from object`)

		return nil, diags
	}

	preferredChainVal, ok := preferredChainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`preferred_chain expected to be basetypes.StringValue, was: %T`, preferredChainAttribute))
	}

	verificationMethodAttribute, ok := attributes["verification_method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`verification_method is missing from object`)

		return nil, diags
	}

	verificationMethodVal, ok := verificationMethodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`verification_method expected to be basetypes.StringValue, was: %T`, verificationMethodAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LetsencryptValue{
		KeyType:            keyTypeVal,
		PreferredChain:     preferredChainVal,
		VerificationMethod: verificationMethodVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewLetsencryptValueNull() LetsencryptValue {
	return LetsencryptValue{
		state: attr.ValueStateNull,
	}
}

func NewLetsencryptValueUnknown() LetsencryptValue {
	return LetsencryptValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLetsencryptValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LetsencryptValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LetsencryptValue Attribute Value",
				"While creating a LetsencryptValue value, a missing attribute value was detected. "+
					"A LetsencryptValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LetsencryptValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LetsencryptValue Attribute Type",
				"While creating a LetsencryptValue value, an invalid attribute value was detected. "+
					"A LetsencryptValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LetsencryptValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LetsencryptValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LetsencryptValue Attribute Value",
				"While creating a LetsencryptValue value, an extra attribute value was detected. "+
					"A LetsencryptValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LetsencryptValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLetsencryptValueUnknown(), diags
	}

	keyTypeAttribute, ok := attributes["key_type"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key_type is missing from object`)

		return NewLetsencryptValueUnknown(), diags
	}

	keyTypeVal, ok := keyTypeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key_type expected to be basetypes.StringValue, was: %T`, keyTypeAttribute))
	}

	preferredChainAttribute, ok := attributes["preferred_chain"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`preferred_chain is missing from object`)

		return NewLetsencryptValueUnknown(), diags
	}

	preferredChainVal, ok := preferredChainAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`preferred_chain expected to be basetypes.StringValue, was: %T`, preferredChainAttribute))
	}

	verificationMethodAttribute, ok := attributes["verification_method"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`verification_method is missing from object`)

		return NewLetsencryptValueUnknown(), diags
	}

	verificationMethodVal, ok := verificationMethodAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`verification_method expected to be basetypes.StringValue, was: %T`, verificationMethodAttribute))
	}

	if diags.HasError() {
		return NewLetsencryptValueUnknown(), diags
	}

	return LetsencryptValue{
		KeyType:            keyTypeVal,
		PreferredChain:     preferredChainVal,
		VerificationMethod: verificationMethodVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewLetsencryptValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LetsencryptValue {
	object, diags := NewLetsencryptValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLetsencryptValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LetsencryptType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLetsencryptValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLetsencryptValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLetsencryptValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLetsencryptValueMust(LetsencryptValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LetsencryptType) ValueType(ctx context.Context) attr.Value {
	return LetsencryptValue{}
}

var _ basetypes.ObjectValuable = LetsencryptValue{}

type LetsencryptValue struct {
	KeyType            basetypes.StringValue `tfsdk:"key_type"`
	PreferredChain     basetypes.StringValue `tfsdk:"preferred_chain"`
	VerificationMethod basetypes.StringValue `tfsdk:"verification_method"`
	state              attr.ValueState
}

func (v LetsencryptValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["key_type"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["preferred_chain"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["verification_method"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.KeyType.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key_type"] = val

		val, err = v.PreferredChain.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["preferred_chain"] = val

		val, err = v.VerificationMethod.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["verification_method"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LetsencryptValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LetsencryptValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LetsencryptValue) String() string {
	return "LetsencryptValue"
}

func (v LetsencryptValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"key_type":            basetypes.StringType{},
		"preferred_chain":     basetypes.StringType{},
		"verification_method": basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"key_type":            v.KeyType,
			"preferred_chain":     v.PreferredChain,
			"verification_method": v.VerificationMethod,
		})

	return objVal, diags
}

func (v LetsencryptValue) Equal(o attr.Value) bool {
	other, ok := o.(LetsencryptValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.KeyType.Equal(other.KeyType) {
		return false
	}

	if !v.PreferredChain.Equal(other.PreferredChain) {
		return false
	}

	if !v.VerificationMethod.Equal(other.VerificationMethod) {
		return false
	}

	return true
}

func (v LetsencryptValue) Type(ctx context.Context) attr.Type {
	return LetsencryptType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LetsencryptValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"key_type":            basetypes.StringType{},
		"preferred_chain":     basetypes.StringType{},
		"verification_method": basetypes.StringType{},
	}
}
