// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_region_vpcs

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RegionVpcsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"cidr_block": schema.StringAttribute{
				Computed: true,
			},
			"credential": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The credential ID",
				MarkdownDescription: "The credential ID",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the vpc",
				MarkdownDescription: "The name of the vpc",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
				},
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"region": schema.StringAttribute{
				Computed: true,
			},
			"subnets": schema.StringAttribute{
				Computed: true,
			},
			"vpc_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
		},
	}
}

type RegionVpcsModel struct {
	CidrBlock    types.String `tfsdk:"cidr_block"`
	Credential   types.Int64  `tfsdk:"credential"`
	Id           types.String `tfsdk:"id"`
	Name         types.String `tfsdk:"name"`
	Organization types.String `tfsdk:"organization"`
	Region       types.String `tfsdk:"region"`
	Subnets      types.String `tfsdk:"subnets"`
	VpcId        types.String `tfsdk:"vpc_id"`
}
