// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_recipe_runs

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func RecipeRunsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"email": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether to send an email notification when the recipe has completed.",
				MarkdownDescription: "Whether to send an email notification when the recipe has completed.",
			},
			"executed_by": schema.Int64Attribute{
				Computed: true,
			},
			"finished_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"log": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The log ID",
				MarkdownDescription: "The log ID",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"output": schema.StringAttribute{
				Computed: true,
			},
			"recipe": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The recipe ID",
				MarkdownDescription: "The recipe ID",
			},
			"recipe_id": schema.Int64Attribute{
				Computed: true,
			},
			"server_id": schema.Int64Attribute{
				Computed: true,
			},
			"servers": schema.ListAttribute{
				ElementType:         types.Int64Type,
				Required:            true,
				Description:         "The servers on which to run the recipe on.",
				MarkdownDescription: "The servers on which to run the recipe on.",
			},
			"started_at": schema.StringAttribute{
				Computed: true,
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type RecipeRunsModel struct {
	Email        types.Bool   `tfsdk:"email"`
	ExecutedBy   types.Int64  `tfsdk:"executed_by"`
	FinishedAt   types.String `tfsdk:"finished_at"`
	Id           types.String `tfsdk:"id"`
	Log          types.Int64  `tfsdk:"log"`
	Organization types.String `tfsdk:"organization"`
	Output       types.String `tfsdk:"output"`
	Recipe       types.Int64  `tfsdk:"recipe"`
	RecipeId     types.Int64  `tfsdk:"recipe_id"`
	ServerId     types.Int64  `tfsdk:"server_id"`
	Servers      types.List   `tfsdk:"servers"`
	StartedAt    types.String `tfsdk:"started_at"`
	Status       types.String `tfsdk:"status"`
}
