// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_team_invites

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func TeamInvitesResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"email": schema.StringAttribute{
				Required: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"invitation": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The invitation ID",
				MarkdownDescription: "The invitation ID",
			},
			"organization": schema.StringAttribute{
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"role": schema.StringAttribute{
				Computed: true,
			},
			"role_id": schema.Int64Attribute{
				Required: true,
			},
			"team": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type TeamInvitesModel struct {
	CreatedAt    types.String `tfsdk:"created_at"`
	Email        types.String `tfsdk:"email"`
	Id           types.String `tfsdk:"id"`
	Invitation   types.Int64  `tfsdk:"invitation"`
	Organization types.String `tfsdk:"organization"`
	Role         types.String `tfsdk:"role"`
	RoleId       types.Int64  `tfsdk:"role_id"`
	Team         types.String `tfsdk:"team"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
}
