// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_server_scheduled_jobs

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServerScheduledJobsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"command": schema.StringAttribute{
				Required:            true,
				Description:         "The command to run.",
				MarkdownDescription: "The command to run.",
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"cron": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The cron expression to use for the scheduled job. Only used if frequency is set to Custom.",
				MarkdownDescription: "The cron expression to use for the scheduled job. Only used if frequency is set to Custom.",
			},
			"frequency": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"minutely",
						"hourly",
						"nightly",
						"weekly",
						"monthly",
						"reboot",
						"custom",
					),
				},
			},
			"grace_period": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The grace period, in minutes, for the heartbeat.",
				MarkdownDescription: "The grace period, in minutes, for the heartbeat.",
			},
			"heartbeat": schema.BoolAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Whether a heartbeat should be created for the scheduled job.",
				MarkdownDescription: "Whether a heartbeat should be created for the scheduled job.",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"job": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The job ID",
				MarkdownDescription: "The job ID",
			},
			"name": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The name of the command.",
				MarkdownDescription: "The name of the command.",
			},
			"next_run_time": schema.StringAttribute{
				Computed: true,
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
			"user": schema.StringAttribute{
				Required:            true,
				Description:         "The user to run the scheduled job as.",
				MarkdownDescription: "The user to run the scheduled job as.",
			},
		},
	}
}

type ServerScheduledJobsModel struct {
	Command      types.String `tfsdk:"command"`
	CreatedAt    types.String `tfsdk:"created_at"`
	Cron         types.String `tfsdk:"cron"`
	Frequency    types.String `tfsdk:"frequency"`
	GracePeriod  types.String `tfsdk:"grace_period"`
	Heartbeat    types.Bool   `tfsdk:"heartbeat"`
	Id           types.String `tfsdk:"id"`
	Job          types.Int64  `tfsdk:"job"`
	Name         types.String `tfsdk:"name"`
	NextRunTime  types.String `tfsdk:"next_run_time"`
	Organization types.String `tfsdk:"organization"`
	Server       types.Int64  `tfsdk:"server"`
	Status       types.String `tfsdk:"status"`
	UpdatedAt    types.String `tfsdk:"updated_at"`
	User         types.String `tfsdk:"user"`
}
