// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_site_domains

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SiteDomainsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allow_wildcard_subdomains": schema.BoolAttribute{
				Required:            true,
				Description:         "Whether to allow wildcard subdomains for the domain.",
				MarkdownDescription: "Whether to allow wildcard subdomains for the domain.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the domain was created.",
				MarkdownDescription: "The date and time the domain was created.",
			},
			"domain_record": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The domain record ID",
				MarkdownDescription: "The domain record ID",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the domain.",
				MarkdownDescription: "The name of the domain.",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The site ID",
				MarkdownDescription: "The site ID",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the domain was last updated.",
				MarkdownDescription: "The date and time the domain was last updated.",
			},
			"www_redirect_type": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"from-www",
						"to-www",
						"none",
					),
				},
			},
		},
	}
}

type SiteDomainsModel struct {
	AllowWildcardSubdomains types.Bool   `tfsdk:"allow_wildcard_subdomains"`
	CreatedAt               types.String `tfsdk:"created_at"`
	DomainRecord            types.Int64  `tfsdk:"domain_record"`
	Id                      types.String `tfsdk:"id"`
	Name                    types.String `tfsdk:"name"`
	Organization            types.String `tfsdk:"organization"`
	Server                  types.Int64  `tfsdk:"server"`
	Site                    types.Int64  `tfsdk:"site"`
	Status                  types.String `tfsdk:"status"`
	UpdatedAt               types.String `tfsdk:"updated_at"`
	WwwRedirectType         types.String `tfsdk:"www_redirect_type"`
}
