// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_heartbeats

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func HeartbeatsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"custom_frequency": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "A cron expression representing the custom frequency at which the client is expected to send a ping, if the frequency is set to -1.",
				MarkdownDescription: "A cron expression representing the custom frequency at which the client is expected to send a ping, if the frequency is set to -1.",
			},
			"frequency": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.OneOf(
						1,
						5,
						10,
						30,
						60,
						1440,
						10080,
						312480,
						-1,
					),
				},
			},
			"grace_period": schema.Int64Attribute{
				Required: true,
				Validators: []validator.Int64{
					int64validator.OneOf(
						1,
						2,
						5,
						10,
						30,
						60,
					),
				},
			},
			"heartbeat": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The heartbeat ID",
				MarkdownDescription: "The heartbeat ID",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the heartbeat.",
				MarkdownDescription: "The name of the heartbeat.",
				Validators: []validator.String{
					stringvalidator.LengthAtMost(255),
				},
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"ping_url": schema.StringAttribute{
				Computed: true,
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The site ID",
				MarkdownDescription: "The site ID",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type HeartbeatsModel struct {
	CustomFrequency types.String `tfsdk:"custom_frequency"`
	Frequency       types.Int64  `tfsdk:"frequency"`
	GracePeriod     types.Int64  `tfsdk:"grace_period"`
	Heartbeat       types.Int64  `tfsdk:"heartbeat"`
	Id              types.String `tfsdk:"id"`
	Name            types.String `tfsdk:"name"`
	Organization    types.String `tfsdk:"organization"`
	PingUrl         types.String `tfsdk:"ping_url"`
	Server          types.Int64  `tfsdk:"server"`
	Site            types.Int64  `tfsdk:"site"`
	Status          types.String `tfsdk:"status"`
}
