// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_site_commands

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func SiteCommandsResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"command": schema.StringAttribute{
				Computed:            true,
				Description:         "The command that ran.",
				MarkdownDescription: "The command that ran.",
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the command was created.",
				MarkdownDescription: "The date and time the command was created.",
			},
			"duration": schema.StringAttribute{
				Computed:            true,
				Description:         "The duration of the command in human-readable format.",
				MarkdownDescription: "The duration of the command in human-readable format.",
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"opcache_enabled": schema.BoolAttribute{
				Required: true,
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"site": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The site ID",
				MarkdownDescription: "The site ID",
			},
			"status": schema.StringAttribute{
				Computed: true,
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the command was last updated.",
				MarkdownDescription: "The date and time the command was last updated.",
			},
			"user": schema.StringAttribute{
				Computed: true,
			},
			"user_id": schema.Int64Attribute{
				Computed:            true,
				Description:         "The ID of the user who initiated the command.",
				MarkdownDescription: "The ID of the user who initiated the command.",
			},
		},
	}
}

type SiteCommandsModel struct {
	Command        types.String `tfsdk:"command"`
	CreatedAt      types.String `tfsdk:"created_at"`
	Duration       types.String `tfsdk:"duration"`
	Id             types.String `tfsdk:"id"`
	OpcacheEnabled types.Bool   `tfsdk:"opcache_enabled"`
	Organization   types.String `tfsdk:"organization"`
	Server         types.Int64  `tfsdk:"server"`
	Site           types.Int64  `tfsdk:"site"`
	Status         types.String `tfsdk:"status"`
	UpdatedAt      types.String `tfsdk:"updated_at"`
	User           types.String `tfsdk:"user"`
	UserId         types.Int64  `tfsdk:"user_id"`
}
