// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_nginx_templates

import (
	"context"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func NginxTemplatesResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"content": schema.StringAttribute{
				Required:            true,
				Description:         "The content of the Nginx template.",
				MarkdownDescription: "The content of the Nginx template.",
			},
			"created_at": schema.StringAttribute{
				Computed: true,
			},
			"id": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the Nginx template.",
				MarkdownDescription: "The name of the Nginx template.",
			},
			"nginx_template": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The nginx template ID",
				MarkdownDescription: "The nginx template ID",
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"updated_at": schema.StringAttribute{
				Computed: true,
			},
		},
	}
}

type NginxTemplatesModel struct {
	Content       types.String `tfsdk:"content"`
	CreatedAt     types.String `tfsdk:"created_at"`
	Id            types.String `tfsdk:"id"`
	Name          types.String `tfsdk:"name"`
	NginxTemplate types.Int64  `tfsdk:"nginx_template"`
	Organization  types.String `tfsdk:"organization"`
	Server        types.Int64  `tfsdk:"server"`
	UpdatedAt     types.String `tfsdk:"updated_at"`
}
