// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_servers

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/booldefault"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func ServersResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"add_key_to_source_control": schema.BoolAttribute{
				Optional: true,
				Computed: true,
				Default:  booldefault.StaticBool(true),
			},
			"akamai": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: AkamaiType{
					ObjectType: types.ObjectType{
						AttrTypes: AkamaiValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"aws": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"disk_size": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"subnet_uuid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"vpc_uuid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: AwsType{
					ObjectType: types.ObjectType{
						AttrTypes: AwsValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"cloud_provider": schema.StringAttribute{
				Required: true,
			},
			"connection_status": schema.StringAttribute{
				Computed: true,
			},
			"created_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the server was created.",
				MarkdownDescription: "The date and time the server was created.",
			},
			"credential_id": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"custom": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"behind_nat": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"ip_address": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"nat_ssh_port": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"private_ip_address": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"ssh_port": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: CustomType{
					ObjectType: types.ObjectType{
						AttrTypes: CustomValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"database": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"database_type": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"db_status": schema.StringAttribute{
				Computed: true,
			},
			"hetzner": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"enable_daily_backups": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"network_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: HetznerType{
					ObjectType: types.ObjectType{
						AttrTypes: HetznerValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"id": schema.Int64Attribute{
				Computed: true,
			},
			"identifier": schema.StringAttribute{
				Computed: true,
			},
			"ip_address": schema.StringAttribute{
				Computed: true,
			},
			"is_ready": schema.BoolAttribute{
				Computed: true,
			},
			"laravel": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"vpc_uuid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: LaravelType{
					ObjectType: types.ObjectType{
						AttrTypes: LaravelValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"local_public_key": schema.StringAttribute{
				Computed: true,
			},
			"name": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.LengthAtMost(30),
				},
			},
			"ocean2": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"enable_weekly_backups": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"vpc_uuid": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: Ocean2Type{
					ObjectType: types.ObjectType{
						AttrTypes: Ocean2Value{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
			"opcache_status": schema.StringAttribute{
				Computed: true,
			},
			"organization": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "The organization slug",
				MarkdownDescription: "The organization slug",
			},
			"php_cli_version": schema.StringAttribute{
				Computed: true,
			},
			"php_version": schema.StringAttribute{
				Optional: true,
				Computed: true,
			},
			"private_ip_address": schema.StringAttribute{
				Computed: true,
			},
			"recipe_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"redis_status": schema.StringAttribute{
				Computed: true,
			},
			"region": schema.StringAttribute{
				Computed: true,
			},
			"revoked": schema.BoolAttribute{
				Computed: true,
			},
			"server": schema.Int64Attribute{
				Optional:            true,
				Computed:            true,
				Description:         "The server ID",
				MarkdownDescription: "The server ID",
			},
			"size": schema.StringAttribute{
				Computed: true,
			},
			"ssh_port": schema.Int64Attribute{
				Computed: true,
			},
			"tags": schema.ListAttribute{
				ElementType: types.StringType,
				Optional:    true,
				Computed:    true,
			},
			"team_id": schema.Int64Attribute{
				Optional: true,
				Computed: true,
			},
			"timezone": schema.StringAttribute{
				Computed: true,
			},
			"type": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"app",
						"web",
						"loadbalancer",
						"database",
						"cache",
						"worker",
						"meilisearch",
					),
				},
			},
			"ubuntu_version": schema.StringAttribute{
				Required: true,
				Validators: []validator.String{
					stringvalidator.OneOf(
						"22.04",
						"24.04",
					),
				},
			},
			"updated_at": schema.StringAttribute{
				Computed:            true,
				Description:         "The date and time the server was last updated.",
				MarkdownDescription: "The date and time the server was last updated.",
			},
			"vultr": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"network_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"region_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
					"size_id": schema.StringAttribute{
						Optional: true,
						Computed: true,
					},
				},
				CustomType: VultrType{
					ObjectType: types.ObjectType{
						AttrTypes: VultrValue{}.AttributeTypes(ctx),
					},
				},
				Optional: true,
				Computed: true,
			},
		},
	}
}

type ServersModel struct {
	AddKeyToSourceControl types.Bool   `tfsdk:"add_key_to_source_control"`
	Akamai                AkamaiValue  `tfsdk:"akamai"`
	Aws                   AwsValue     `tfsdk:"aws"`
	CloudProvider         types.String `tfsdk:"cloud_provider"`
	ConnectionStatus      types.String `tfsdk:"connection_status"`
	CreatedAt             types.String `tfsdk:"created_at"`
	CredentialId          types.String `tfsdk:"credential_id"`
	Custom                CustomValue  `tfsdk:"custom"`
	Database              types.String `tfsdk:"database"`
	DatabaseType          types.String `tfsdk:"database_type"`
	DbStatus              types.String `tfsdk:"db_status"`
	Hetzner               HetznerValue `tfsdk:"hetzner"`
	Id                    types.Int64  `tfsdk:"id"`
	Identifier            types.String `tfsdk:"identifier"`
	IpAddress             types.String `tfsdk:"ip_address"`
	IsReady               types.Bool   `tfsdk:"is_ready"`
	Laravel               LaravelValue `tfsdk:"laravel"`
	LocalPublicKey        types.String `tfsdk:"local_public_key"`
	Name                  types.String `tfsdk:"name"`
	Ocean2                Ocean2Value  `tfsdk:"ocean2"`
	OpcacheStatus         types.String `tfsdk:"opcache_status"`
	Organization          types.String `tfsdk:"organization"`
	PhpCliVersion         types.String `tfsdk:"php_cli_version"`
	PhpVersion            types.String `tfsdk:"php_version"`
	PrivateIpAddress      types.String `tfsdk:"private_ip_address"`
	RecipeId              types.Int64  `tfsdk:"recipe_id"`
	RedisStatus           types.String `tfsdk:"redis_status"`
	Region                types.String `tfsdk:"region"`
	Revoked               types.Bool   `tfsdk:"revoked"`
	Server                types.Int64  `tfsdk:"server"`
	Size                  types.String `tfsdk:"size"`
	SshPort               types.Int64  `tfsdk:"ssh_port"`
	Tags                  types.List   `tfsdk:"tags"`
	TeamId                types.Int64  `tfsdk:"team_id"`
	Timezone              types.String `tfsdk:"timezone"`
	Type                  types.String `tfsdk:"type"`
	UbuntuVersion         types.String `tfsdk:"ubuntu_version"`
	UpdatedAt             types.String `tfsdk:"updated_at"`
	Vultr                 VultrValue   `tfsdk:"vultr"`
}

var _ basetypes.ObjectTypable = AkamaiType{}

type AkamaiType struct {
	basetypes.ObjectType
}

func (t AkamaiType) Equal(o attr.Type) bool {
	other, ok := o.(AkamaiType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AkamaiType) String() string {
	return "AkamaiType"
}

func (t AkamaiType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AkamaiValue{
		RegionId: regionIdVal,
		SizeId:   sizeIdVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewAkamaiValueNull() AkamaiValue {
	return AkamaiValue{
		state: attr.ValueStateNull,
	}
}

func NewAkamaiValueUnknown() AkamaiValue {
	return AkamaiValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAkamaiValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AkamaiValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AkamaiValue Attribute Value",
				"While creating a AkamaiValue value, a missing attribute value was detected. "+
					"A AkamaiValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AkamaiValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AkamaiValue Attribute Type",
				"While creating a AkamaiValue value, an invalid attribute value was detected. "+
					"A AkamaiValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AkamaiValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AkamaiValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AkamaiValue Attribute Value",
				"While creating a AkamaiValue value, an extra attribute value was detected. "+
					"A AkamaiValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AkamaiValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAkamaiValueUnknown(), diags
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewAkamaiValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewAkamaiValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return NewAkamaiValueUnknown(), diags
	}

	return AkamaiValue{
		RegionId: regionIdVal,
		SizeId:   sizeIdVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewAkamaiValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AkamaiValue {
	object, diags := NewAkamaiValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAkamaiValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AkamaiType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAkamaiValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAkamaiValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAkamaiValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAkamaiValueMust(AkamaiValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AkamaiType) ValueType(ctx context.Context) attr.Value {
	return AkamaiValue{}
}

var _ basetypes.ObjectValuable = AkamaiValue{}

type AkamaiValue struct {
	RegionId basetypes.StringValue `tfsdk:"region_id"`
	SizeId   basetypes.StringValue `tfsdk:"size_id"`
	state    attr.ValueState
}

func (v AkamaiValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AkamaiValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AkamaiValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AkamaiValue) String() string {
	return "AkamaiValue"
}

func (v AkamaiValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"region_id": basetypes.StringType{},
		"size_id":   basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"region_id": v.RegionId,
			"size_id":   v.SizeId,
		})

	return objVal, diags
}

func (v AkamaiValue) Equal(o attr.Value) bool {
	other, ok := o.(AkamaiValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	return true
}

func (v AkamaiValue) Type(ctx context.Context) attr.Type {
	return AkamaiType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AkamaiValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"region_id": basetypes.StringType{},
		"size_id":   basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = AwsType{}

type AwsType struct {
	basetypes.ObjectType
}

func (t AwsType) Equal(o attr.Type) bool {
	other, ok := o.(AwsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AwsType) String() string {
	return "AwsType"
}

func (t AwsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	diskSizeAttribute, ok := attributes["disk_size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disk_size is missing from object`)

		return nil, diags
	}

	diskSizeVal, ok := diskSizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disk_size expected to be basetypes.StringValue, was: %T`, diskSizeAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	subnetUuidAttribute, ok := attributes["subnet_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subnet_uuid is missing from object`)

		return nil, diags
	}

	subnetUuidVal, ok := subnetUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subnet_uuid expected to be basetypes.StringValue, was: %T`, subnetUuidAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return nil, diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AwsValue{
		DiskSize:   diskSizeVal,
		RegionId:   regionIdVal,
		SizeId:     sizeIdVal,
		SubnetUuid: subnetUuidVal,
		VpcUuid:    vpcUuidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAwsValueNull() AwsValue {
	return AwsValue{
		state: attr.ValueStateNull,
	}
}

func NewAwsValueUnknown() AwsValue {
	return AwsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAwsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AwsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AwsValue Attribute Value",
				"While creating a AwsValue value, a missing attribute value was detected. "+
					"A AwsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AwsValue Attribute Type",
				"While creating a AwsValue value, an invalid attribute value was detected. "+
					"A AwsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AwsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AwsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AwsValue Attribute Value",
				"While creating a AwsValue value, an extra attribute value was detected. "+
					"A AwsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AwsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAwsValueUnknown(), diags
	}

	diskSizeAttribute, ok := attributes["disk_size"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`disk_size is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	diskSizeVal, ok := diskSizeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`disk_size expected to be basetypes.StringValue, was: %T`, diskSizeAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	subnetUuidAttribute, ok := attributes["subnet_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`subnet_uuid is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	subnetUuidVal, ok := subnetUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`subnet_uuid expected to be basetypes.StringValue, was: %T`, subnetUuidAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return NewAwsValueUnknown(), diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return NewAwsValueUnknown(), diags
	}

	return AwsValue{
		DiskSize:   diskSizeVal,
		RegionId:   regionIdVal,
		SizeId:     sizeIdVal,
		SubnetUuid: subnetUuidVal,
		VpcUuid:    vpcUuidVal,
		state:      attr.ValueStateKnown,
	}, diags
}

func NewAwsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AwsValue {
	object, diags := NewAwsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAwsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AwsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAwsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAwsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAwsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAwsValueMust(AwsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AwsType) ValueType(ctx context.Context) attr.Value {
	return AwsValue{}
}

var _ basetypes.ObjectValuable = AwsValue{}

type AwsValue struct {
	DiskSize   basetypes.StringValue `tfsdk:"disk_size"`
	RegionId   basetypes.StringValue `tfsdk:"region_id"`
	SizeId     basetypes.StringValue `tfsdk:"size_id"`
	SubnetUuid basetypes.StringValue `tfsdk:"subnet_uuid"`
	VpcUuid    basetypes.StringValue `tfsdk:"vpc_uuid"`
	state      attr.ValueState
}

func (v AwsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["disk_size"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["subnet_uuid"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vpc_uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.DiskSize.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["disk_size"] = val

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		val, err = v.SubnetUuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["subnet_uuid"] = val

		val, err = v.VpcUuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vpc_uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AwsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AwsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AwsValue) String() string {
	return "AwsValue"
}

func (v AwsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"disk_size":   basetypes.StringType{},
		"region_id":   basetypes.StringType{},
		"size_id":     basetypes.StringType{},
		"subnet_uuid": basetypes.StringType{},
		"vpc_uuid":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"disk_size":   v.DiskSize,
			"region_id":   v.RegionId,
			"size_id":     v.SizeId,
			"subnet_uuid": v.SubnetUuid,
			"vpc_uuid":    v.VpcUuid,
		})

	return objVal, diags
}

func (v AwsValue) Equal(o attr.Value) bool {
	other, ok := o.(AwsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.DiskSize.Equal(other.DiskSize) {
		return false
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	if !v.SubnetUuid.Equal(other.SubnetUuid) {
		return false
	}

	if !v.VpcUuid.Equal(other.VpcUuid) {
		return false
	}

	return true
}

func (v AwsValue) Type(ctx context.Context) attr.Type {
	return AwsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AwsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"disk_size":   basetypes.StringType{},
		"region_id":   basetypes.StringType{},
		"size_id":     basetypes.StringType{},
		"subnet_uuid": basetypes.StringType{},
		"vpc_uuid":    basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = CustomType{}

type CustomType struct {
	basetypes.ObjectType
}

func (t CustomType) Equal(o attr.Type) bool {
	other, ok := o.(CustomType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t CustomType) String() string {
	return "CustomType"
}

func (t CustomType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	behindNatAttribute, ok := attributes["behind_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`behind_nat is missing from object`)

		return nil, diags
	}

	behindNatVal, ok := behindNatAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`behind_nat expected to be basetypes.StringValue, was: %T`, behindNatAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return nil, diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	natSshPortAttribute, ok := attributes["nat_ssh_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`nat_ssh_port is missing from object`)

		return nil, diags
	}

	natSshPortVal, ok := natSshPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`nat_ssh_port expected to be basetypes.StringValue, was: %T`, natSshPortAttribute))
	}

	privateIpAddressAttribute, ok := attributes["private_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_ip_address is missing from object`)

		return nil, diags
	}

	privateIpAddressVal, ok := privateIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_ip_address expected to be basetypes.StringValue, was: %T`, privateIpAddressAttribute))
	}

	sshPortAttribute, ok := attributes["ssh_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssh_port is missing from object`)

		return nil, diags
	}

	sshPortVal, ok := sshPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssh_port expected to be basetypes.StringValue, was: %T`, sshPortAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return CustomValue{
		BehindNat:        behindNatVal,
		IpAddress:        ipAddressVal,
		NatSshPort:       natSshPortVal,
		PrivateIpAddress: privateIpAddressVal,
		SshPort:          sshPortVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewCustomValueNull() CustomValue {
	return CustomValue{
		state: attr.ValueStateNull,
	}
}

func NewCustomValueUnknown() CustomValue {
	return CustomValue{
		state: attr.ValueStateUnknown,
	}
}

func NewCustomValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (CustomValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing CustomValue Attribute Value",
				"While creating a CustomValue value, a missing attribute value was detected. "+
					"A CustomValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CustomValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid CustomValue Attribute Type",
				"While creating a CustomValue value, an invalid attribute value was detected. "+
					"A CustomValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("CustomValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("CustomValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra CustomValue Attribute Value",
				"While creating a CustomValue value, an extra attribute value was detected. "+
					"A CustomValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra CustomValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewCustomValueUnknown(), diags
	}

	behindNatAttribute, ok := attributes["behind_nat"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`behind_nat is missing from object`)

		return NewCustomValueUnknown(), diags
	}

	behindNatVal, ok := behindNatAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`behind_nat expected to be basetypes.StringValue, was: %T`, behindNatAttribute))
	}

	ipAddressAttribute, ok := attributes["ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ip_address is missing from object`)

		return NewCustomValueUnknown(), diags
	}

	ipAddressVal, ok := ipAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ip_address expected to be basetypes.StringValue, was: %T`, ipAddressAttribute))
	}

	natSshPortAttribute, ok := attributes["nat_ssh_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`nat_ssh_port is missing from object`)

		return NewCustomValueUnknown(), diags
	}

	natSshPortVal, ok := natSshPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`nat_ssh_port expected to be basetypes.StringValue, was: %T`, natSshPortAttribute))
	}

	privateIpAddressAttribute, ok := attributes["private_ip_address"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`private_ip_address is missing from object`)

		return NewCustomValueUnknown(), diags
	}

	privateIpAddressVal, ok := privateIpAddressAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`private_ip_address expected to be basetypes.StringValue, was: %T`, privateIpAddressAttribute))
	}

	sshPortAttribute, ok := attributes["ssh_port"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`ssh_port is missing from object`)

		return NewCustomValueUnknown(), diags
	}

	sshPortVal, ok := sshPortAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`ssh_port expected to be basetypes.StringValue, was: %T`, sshPortAttribute))
	}

	if diags.HasError() {
		return NewCustomValueUnknown(), diags
	}

	return CustomValue{
		BehindNat:        behindNatVal,
		IpAddress:        ipAddressVal,
		NatSshPort:       natSshPortVal,
		PrivateIpAddress: privateIpAddressVal,
		SshPort:          sshPortVal,
		state:            attr.ValueStateKnown,
	}, diags
}

func NewCustomValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) CustomValue {
	object, diags := NewCustomValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewCustomValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t CustomType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewCustomValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewCustomValueUnknown(), nil
	}

	if in.IsNull() {
		return NewCustomValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewCustomValueMust(CustomValue{}.AttributeTypes(ctx), attributes), nil
}

func (t CustomType) ValueType(ctx context.Context) attr.Value {
	return CustomValue{}
}

var _ basetypes.ObjectValuable = CustomValue{}

type CustomValue struct {
	BehindNat        basetypes.StringValue `tfsdk:"behind_nat"`
	IpAddress        basetypes.StringValue `tfsdk:"ip_address"`
	NatSshPort       basetypes.StringValue `tfsdk:"nat_ssh_port"`
	PrivateIpAddress basetypes.StringValue `tfsdk:"private_ip_address"`
	SshPort          basetypes.StringValue `tfsdk:"ssh_port"`
	state            attr.ValueState
}

func (v CustomValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 5)

	var val tftypes.Value
	var err error

	attrTypes["behind_nat"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["nat_ssh_port"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["private_ip_address"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["ssh_port"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 5)

		val, err = v.BehindNat.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["behind_nat"] = val

		val, err = v.IpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ip_address"] = val

		val, err = v.NatSshPort.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["nat_ssh_port"] = val

		val, err = v.PrivateIpAddress.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["private_ip_address"] = val

		val, err = v.SshPort.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["ssh_port"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v CustomValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v CustomValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v CustomValue) String() string {
	return "CustomValue"
}

func (v CustomValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"behind_nat":         basetypes.StringType{},
		"ip_address":         basetypes.StringType{},
		"nat_ssh_port":       basetypes.StringType{},
		"private_ip_address": basetypes.StringType{},
		"ssh_port":           basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"behind_nat":         v.BehindNat,
			"ip_address":         v.IpAddress,
			"nat_ssh_port":       v.NatSshPort,
			"private_ip_address": v.PrivateIpAddress,
			"ssh_port":           v.SshPort,
		})

	return objVal, diags
}

func (v CustomValue) Equal(o attr.Value) bool {
	other, ok := o.(CustomValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BehindNat.Equal(other.BehindNat) {
		return false
	}

	if !v.IpAddress.Equal(other.IpAddress) {
		return false
	}

	if !v.NatSshPort.Equal(other.NatSshPort) {
		return false
	}

	if !v.PrivateIpAddress.Equal(other.PrivateIpAddress) {
		return false
	}

	if !v.SshPort.Equal(other.SshPort) {
		return false
	}

	return true
}

func (v CustomValue) Type(ctx context.Context) attr.Type {
	return CustomType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v CustomValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"behind_nat":         basetypes.StringType{},
		"ip_address":         basetypes.StringType{},
		"nat_ssh_port":       basetypes.StringType{},
		"private_ip_address": basetypes.StringType{},
		"ssh_port":           basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = HetznerType{}

type HetznerType struct {
	basetypes.ObjectType
}

func (t HetznerType) Equal(o attr.Type) bool {
	other, ok := o.(HetznerType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t HetznerType) String() string {
	return "HetznerType"
}

func (t HetznerType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	enableDailyBackupsAttribute, ok := attributes["enable_daily_backups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enable_daily_backups is missing from object`)

		return nil, diags
	}

	enableDailyBackupsVal, ok := enableDailyBackupsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enable_daily_backups expected to be basetypes.StringValue, was: %T`, enableDailyBackupsAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return nil, diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return HetznerValue{
		EnableDailyBackups: enableDailyBackupsVal,
		NetworkId:          networkIdVal,
		RegionId:           regionIdVal,
		SizeId:             sizeIdVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewHetznerValueNull() HetznerValue {
	return HetznerValue{
		state: attr.ValueStateNull,
	}
}

func NewHetznerValueUnknown() HetznerValue {
	return HetznerValue{
		state: attr.ValueStateUnknown,
	}
}

func NewHetznerValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (HetznerValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing HetznerValue Attribute Value",
				"While creating a HetznerValue value, a missing attribute value was detected. "+
					"A HetznerValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HetznerValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid HetznerValue Attribute Type",
				"While creating a HetznerValue value, an invalid attribute value was detected. "+
					"A HetznerValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("HetznerValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("HetznerValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra HetznerValue Attribute Value",
				"While creating a HetznerValue value, an extra attribute value was detected. "+
					"A HetznerValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra HetznerValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewHetznerValueUnknown(), diags
	}

	enableDailyBackupsAttribute, ok := attributes["enable_daily_backups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enable_daily_backups is missing from object`)

		return NewHetznerValueUnknown(), diags
	}

	enableDailyBackupsVal, ok := enableDailyBackupsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enable_daily_backups expected to be basetypes.StringValue, was: %T`, enableDailyBackupsAttribute))
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return NewHetznerValueUnknown(), diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewHetznerValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewHetznerValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return NewHetznerValueUnknown(), diags
	}

	return HetznerValue{
		EnableDailyBackups: enableDailyBackupsVal,
		NetworkId:          networkIdVal,
		RegionId:           regionIdVal,
		SizeId:             sizeIdVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewHetznerValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) HetznerValue {
	object, diags := NewHetznerValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewHetznerValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t HetznerType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewHetznerValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewHetznerValueUnknown(), nil
	}

	if in.IsNull() {
		return NewHetznerValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewHetznerValueMust(HetznerValue{}.AttributeTypes(ctx), attributes), nil
}

func (t HetznerType) ValueType(ctx context.Context) attr.Value {
	return HetznerValue{}
}

var _ basetypes.ObjectValuable = HetznerValue{}

type HetznerValue struct {
	EnableDailyBackups basetypes.StringValue `tfsdk:"enable_daily_backups"`
	NetworkId          basetypes.StringValue `tfsdk:"network_id"`
	RegionId           basetypes.StringValue `tfsdk:"region_id"`
	SizeId             basetypes.StringValue `tfsdk:"size_id"`
	state              attr.ValueState
}

func (v HetznerValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["enable_daily_backups"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["network_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.EnableDailyBackups.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enable_daily_backups"] = val

		val, err = v.NetworkId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_id"] = val

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v HetznerValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v HetznerValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v HetznerValue) String() string {
	return "HetznerValue"
}

func (v HetznerValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"enable_daily_backups": basetypes.StringType{},
		"network_id":           basetypes.StringType{},
		"region_id":            basetypes.StringType{},
		"size_id":              basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"enable_daily_backups": v.EnableDailyBackups,
			"network_id":           v.NetworkId,
			"region_id":            v.RegionId,
			"size_id":              v.SizeId,
		})

	return objVal, diags
}

func (v HetznerValue) Equal(o attr.Value) bool {
	other, ok := o.(HetznerValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EnableDailyBackups.Equal(other.EnableDailyBackups) {
		return false
	}

	if !v.NetworkId.Equal(other.NetworkId) {
		return false
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	return true
}

func (v HetznerValue) Type(ctx context.Context) attr.Type {
	return HetznerType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v HetznerValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"enable_daily_backups": basetypes.StringType{},
		"network_id":           basetypes.StringType{},
		"region_id":            basetypes.StringType{},
		"size_id":              basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = LaravelType{}

type LaravelType struct {
	basetypes.ObjectType
}

func (t LaravelType) Equal(o attr.Type) bool {
	other, ok := o.(LaravelType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t LaravelType) String() string {
	return "LaravelType"
}

func (t LaravelType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return nil, diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return LaravelValue{
		RegionId: regionIdVal,
		SizeId:   sizeIdVal,
		VpcUuid:  vpcUuidVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewLaravelValueNull() LaravelValue {
	return LaravelValue{
		state: attr.ValueStateNull,
	}
}

func NewLaravelValueUnknown() LaravelValue {
	return LaravelValue{
		state: attr.ValueStateUnknown,
	}
}

func NewLaravelValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (LaravelValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing LaravelValue Attribute Value",
				"While creating a LaravelValue value, a missing attribute value was detected. "+
					"A LaravelValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LaravelValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid LaravelValue Attribute Type",
				"While creating a LaravelValue value, an invalid attribute value was detected. "+
					"A LaravelValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("LaravelValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("LaravelValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra LaravelValue Attribute Value",
				"While creating a LaravelValue value, an extra attribute value was detected. "+
					"A LaravelValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra LaravelValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewLaravelValueUnknown(), diags
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewLaravelValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewLaravelValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return NewLaravelValueUnknown(), diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return NewLaravelValueUnknown(), diags
	}

	return LaravelValue{
		RegionId: regionIdVal,
		SizeId:   sizeIdVal,
		VpcUuid:  vpcUuidVal,
		state:    attr.ValueStateKnown,
	}, diags
}

func NewLaravelValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) LaravelValue {
	object, diags := NewLaravelValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewLaravelValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t LaravelType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewLaravelValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewLaravelValueUnknown(), nil
	}

	if in.IsNull() {
		return NewLaravelValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewLaravelValueMust(LaravelValue{}.AttributeTypes(ctx), attributes), nil
}

func (t LaravelType) ValueType(ctx context.Context) attr.Value {
	return LaravelValue{}
}

var _ basetypes.ObjectValuable = LaravelValue{}

type LaravelValue struct {
	RegionId basetypes.StringValue `tfsdk:"region_id"`
	SizeId   basetypes.StringValue `tfsdk:"size_id"`
	VpcUuid  basetypes.StringValue `tfsdk:"vpc_uuid"`
	state    attr.ValueState
}

func (v LaravelValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vpc_uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		val, err = v.VpcUuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vpc_uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v LaravelValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v LaravelValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v LaravelValue) String() string {
	return "LaravelValue"
}

func (v LaravelValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"region_id": basetypes.StringType{},
		"size_id":   basetypes.StringType{},
		"vpc_uuid":  basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"region_id": v.RegionId,
			"size_id":   v.SizeId,
			"vpc_uuid":  v.VpcUuid,
		})

	return objVal, diags
}

func (v LaravelValue) Equal(o attr.Value) bool {
	other, ok := o.(LaravelValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	if !v.VpcUuid.Equal(other.VpcUuid) {
		return false
	}

	return true
}

func (v LaravelValue) Type(ctx context.Context) attr.Type {
	return LaravelType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v LaravelValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"region_id": basetypes.StringType{},
		"size_id":   basetypes.StringType{},
		"vpc_uuid":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = Ocean2Type{}

type Ocean2Type struct {
	basetypes.ObjectType
}

func (t Ocean2Type) Equal(o attr.Type) bool {
	other, ok := o.(Ocean2Type)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t Ocean2Type) String() string {
	return "Ocean2Type"
}

func (t Ocean2Type) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	enableWeeklyBackupsAttribute, ok := attributes["enable_weekly_backups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enable_weekly_backups is missing from object`)

		return nil, diags
	}

	enableWeeklyBackupsVal, ok := enableWeeklyBackupsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enable_weekly_backups expected to be basetypes.StringValue, was: %T`, enableWeeklyBackupsAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return nil, diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return Ocean2Value{
		EnableWeeklyBackups: enableWeeklyBackupsVal,
		RegionId:            regionIdVal,
		SizeId:              sizeIdVal,
		VpcUuid:             vpcUuidVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewOcean2ValueNull() Ocean2Value {
	return Ocean2Value{
		state: attr.ValueStateNull,
	}
}

func NewOcean2ValueUnknown() Ocean2Value {
	return Ocean2Value{
		state: attr.ValueStateUnknown,
	}
}

func NewOcean2Value(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (Ocean2Value, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing Ocean2Value Attribute Value",
				"While creating a Ocean2Value value, a missing attribute value was detected. "+
					"A Ocean2Value must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ocean2Value Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid Ocean2Value Attribute Type",
				"While creating a Ocean2Value value, an invalid attribute value was detected. "+
					"A Ocean2Value must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Ocean2Value Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("Ocean2Value Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra Ocean2Value Attribute Value",
				"While creating a Ocean2Value value, an extra attribute value was detected. "+
					"A Ocean2Value must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra Ocean2Value Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewOcean2ValueUnknown(), diags
	}

	enableWeeklyBackupsAttribute, ok := attributes["enable_weekly_backups"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`enable_weekly_backups is missing from object`)

		return NewOcean2ValueUnknown(), diags
	}

	enableWeeklyBackupsVal, ok := enableWeeklyBackupsAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`enable_weekly_backups expected to be basetypes.StringValue, was: %T`, enableWeeklyBackupsAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewOcean2ValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewOcean2ValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	vpcUuidAttribute, ok := attributes["vpc_uuid"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vpc_uuid is missing from object`)

		return NewOcean2ValueUnknown(), diags
	}

	vpcUuidVal, ok := vpcUuidAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vpc_uuid expected to be basetypes.StringValue, was: %T`, vpcUuidAttribute))
	}

	if diags.HasError() {
		return NewOcean2ValueUnknown(), diags
	}

	return Ocean2Value{
		EnableWeeklyBackups: enableWeeklyBackupsVal,
		RegionId:            regionIdVal,
		SizeId:              sizeIdVal,
		VpcUuid:             vpcUuidVal,
		state:               attr.ValueStateKnown,
	}, diags
}

func NewOcean2ValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) Ocean2Value {
	object, diags := NewOcean2Value(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewOcean2ValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t Ocean2Type) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewOcean2ValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewOcean2ValueUnknown(), nil
	}

	if in.IsNull() {
		return NewOcean2ValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewOcean2ValueMust(Ocean2Value{}.AttributeTypes(ctx), attributes), nil
}

func (t Ocean2Type) ValueType(ctx context.Context) attr.Value {
	return Ocean2Value{}
}

var _ basetypes.ObjectValuable = Ocean2Value{}

type Ocean2Value struct {
	EnableWeeklyBackups basetypes.StringValue `tfsdk:"enable_weekly_backups"`
	RegionId            basetypes.StringValue `tfsdk:"region_id"`
	SizeId              basetypes.StringValue `tfsdk:"size_id"`
	VpcUuid             basetypes.StringValue `tfsdk:"vpc_uuid"`
	state               attr.ValueState
}

func (v Ocean2Value) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 4)

	var val tftypes.Value
	var err error

	attrTypes["enable_weekly_backups"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vpc_uuid"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 4)

		val, err = v.EnableWeeklyBackups.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["enable_weekly_backups"] = val

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		val, err = v.VpcUuid.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vpc_uuid"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v Ocean2Value) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v Ocean2Value) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v Ocean2Value) String() string {
	return "Ocean2Value"
}

func (v Ocean2Value) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"enable_weekly_backups": basetypes.StringType{},
		"region_id":             basetypes.StringType{},
		"size_id":               basetypes.StringType{},
		"vpc_uuid":              basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"enable_weekly_backups": v.EnableWeeklyBackups,
			"region_id":             v.RegionId,
			"size_id":               v.SizeId,
			"vpc_uuid":              v.VpcUuid,
		})

	return objVal, diags
}

func (v Ocean2Value) Equal(o attr.Value) bool {
	other, ok := o.(Ocean2Value)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.EnableWeeklyBackups.Equal(other.EnableWeeklyBackups) {
		return false
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	if !v.VpcUuid.Equal(other.VpcUuid) {
		return false
	}

	return true
}

func (v Ocean2Value) Type(ctx context.Context) attr.Type {
	return Ocean2Type{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v Ocean2Value) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"enable_weekly_backups": basetypes.StringType{},
		"region_id":             basetypes.StringType{},
		"size_id":               basetypes.StringType{},
		"vpc_uuid":              basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = VultrType{}

type VultrType struct {
	basetypes.ObjectType
}

func (t VultrType) Equal(o attr.Type) bool {
	other, ok := o.(VultrType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VultrType) String() string {
	return "VultrType"
}

func (t VultrType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return nil, diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return nil, diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return nil, diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VultrValue{
		NetworkId: networkIdVal,
		RegionId:  regionIdVal,
		SizeId:    sizeIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewVultrValueNull() VultrValue {
	return VultrValue{
		state: attr.ValueStateNull,
	}
}

func NewVultrValueUnknown() VultrValue {
	return VultrValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVultrValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VultrValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VultrValue Attribute Value",
				"While creating a VultrValue value, a missing attribute value was detected. "+
					"A VultrValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VultrValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VultrValue Attribute Type",
				"While creating a VultrValue value, an invalid attribute value was detected. "+
					"A VultrValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VultrValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VultrValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VultrValue Attribute Value",
				"While creating a VultrValue value, an extra attribute value was detected. "+
					"A VultrValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VultrValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVultrValueUnknown(), diags
	}

	networkIdAttribute, ok := attributes["network_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`network_id is missing from object`)

		return NewVultrValueUnknown(), diags
	}

	networkIdVal, ok := networkIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`network_id expected to be basetypes.StringValue, was: %T`, networkIdAttribute))
	}

	regionIdAttribute, ok := attributes["region_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`region_id is missing from object`)

		return NewVultrValueUnknown(), diags
	}

	regionIdVal, ok := regionIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`region_id expected to be basetypes.StringValue, was: %T`, regionIdAttribute))
	}

	sizeIdAttribute, ok := attributes["size_id"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`size_id is missing from object`)

		return NewVultrValueUnknown(), diags
	}

	sizeIdVal, ok := sizeIdAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`size_id expected to be basetypes.StringValue, was: %T`, sizeIdAttribute))
	}

	if diags.HasError() {
		return NewVultrValueUnknown(), diags
	}

	return VultrValue{
		NetworkId: networkIdVal,
		RegionId:  regionIdVal,
		SizeId:    sizeIdVal,
		state:     attr.ValueStateKnown,
	}, diags
}

func NewVultrValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VultrValue {
	object, diags := NewVultrValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVultrValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VultrType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVultrValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVultrValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVultrValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVultrValueMust(VultrValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VultrType) ValueType(ctx context.Context) attr.Value {
	return VultrValue{}
}

var _ basetypes.ObjectValuable = VultrValue{}

type VultrValue struct {
	NetworkId basetypes.StringValue `tfsdk:"network_id"`
	RegionId  basetypes.StringValue `tfsdk:"region_id"`
	SizeId    basetypes.StringValue `tfsdk:"size_id"`
	state     attr.ValueState
}

func (v VultrValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["network_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["region_id"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["size_id"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.NetworkId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["network_id"] = val

		val, err = v.RegionId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["region_id"] = val

		val, err = v.SizeId.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["size_id"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VultrValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VultrValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VultrValue) String() string {
	return "VultrValue"
}

func (v VultrValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributeTypes := map[string]attr.Type{
		"network_id": basetypes.StringType{},
		"region_id":  basetypes.StringType{},
		"size_id":    basetypes.StringType{},
	}

	if v.IsNull() {
		return types.ObjectNull(attributeTypes), diags
	}

	if v.IsUnknown() {
		return types.ObjectUnknown(attributeTypes), diags
	}

	objVal, diags := types.ObjectValue(
		attributeTypes,
		map[string]attr.Value{
			"network_id": v.NetworkId,
			"region_id":  v.RegionId,
			"size_id":    v.SizeId,
		})

	return objVal, diags
}

func (v VultrValue) Equal(o attr.Value) bool {
	other, ok := o.(VultrValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.NetworkId.Equal(other.NetworkId) {
		return false
	}

	if !v.RegionId.Equal(other.RegionId) {
		return false
	}

	if !v.SizeId.Equal(other.SizeId) {
		return false
	}

	return true
}

func (v VultrValue) Type(ctx context.Context) attr.Type {
	return VultrType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VultrValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"network_id": basetypes.StringType{},
		"region_id":  basetypes.StringType{},
		"size_id":    basetypes.StringType{},
	}
}
